#!/usr/bin/env python3
"""
Goldman Sachs Hedge Industry VIP ETF (GVIP) Holdings Monitor
Fetches holdings from stockanalysis.com, performance/AUM from yfinance,
saves a rolling 20-day cache, and publishes an HTML report.

Commentary is generated by Gemma 4 via HuggingFace (refreshed daily).

Flags:
  --cache-only            Skip fetch; use latest cached snapshot
  --no-publish            Generate HTML but skip git push
  --print-context         Print JSON context for Claude to summarize, then exit
  --summary-file PATH     Read summary from file instead of generating
"""

import os
import sys
import json
import time
import argparse
import subprocess
import re
from datetime import datetime, date, timedelta
from pathlib import Path

import requests
from bs4 import BeautifulSoup
import yfinance as yf
from huggingface_hub import InferenceClient

# ── Config ────────────────────────────────────────────────────────────────────

TICKER = "GVIP"
FUND_NAME = "Goldman Sachs Hedge Industry VIP ETF"
FUND_OBJECTIVE = (
    "Seeks to track the Goldman Sachs Hedge Fund VIP Index, which consists of "
    "the 'Very Important Positions' appearing most frequently among hedge fund "
    "managers' top 10 long equity holdings."
)
HOLDINGS_URL = "https://stockanalysis.com/etf/gvip/holdings/"
FUND_PAGE_URL = "https://stockanalysis.com/etf/gvip/"

CACHE_DIR = Path(os.environ.get("GVIP_CACHE_DIR", str(Path.home() / ".claude" / "cache" / "gvip")))
REPORT_DIR = Path(os.environ.get("GVIP_REPORT_DIR", str(Path.home() / "boquin.github.io" / "reports" / "gvip")))
LANDING_PAGE = Path(os.environ.get("GVIP_LANDING_PAGE", str(Path.home() / "boquin.github.io" / "index.html")))

MAX_SNAPSHOTS = 20
SUMMARY_REFRESH_DAYS = 1
SUMMARY_META_FILE = REPORT_DIR / "summary_meta.json"
QUADRANT_META_FILE = REPORT_DIR / "quadrant_meta.json"

MODEL_ID = "google/gemma-4-26B-A4B-it"

SECTOR_LABELS = {
    "technology": "Technology",
    "communication_services": "Communication Services",
    "consumer_cyclical": "Consumer Cyclical",
    "financial_services": "Financial Services",
    "industrials": "Industrials",
    "healthcare": "Healthcare",
    "consumer_defensive": "Consumer Defensive",
    "utilities": "Utilities",
    "basic_materials": "Basic Materials",
    "real_estate": "Real Estate",
    "realestate": "Real Estate",
    "energy": "Energy",
}

SECTOR_COLORS = {
    "technology": "#2563eb",
    "communication_services": "#7c3aed",
    "consumer_cyclical": "#d97706",
    "financial_services": "#16a34a",
    "industrials": "#0891b2",
    "healthcare": "#dc2626",
    "consumer_defensive": "#65a30d",
    "utilities": "#9333ea",
    "basic_materials": "#b45309",
    "real_estate": "#0369a1",
    "realestate": "#0369a1",
    "energy": "#92400e",
}

SYSTEM_PROMPT = """\
You are a macro and equity analyst at a top hedge fund. The user will provide \
you with a structured snapshot of the Goldman Sachs Hedge Industry VIP ETF \
(GVIP): current AUM, performance, top holdings, sector breakdown, and recent \
position changes.

Write a concise analyst commentary (STRICT maximum 400 words) covering: \
what the VIP basket is currently expressing about hedge fund conviction, \
key sector tilts vs the broader market, notable new or removed positions, \
and what the collective positioning implies about macro and earnings expectations.

Open with a 'Key themes' paragraph (2-3 sentences) summarising the dominant \
cross-position bets — what is the hedge fund community collectively expressing?

Style: flowing prose, no bullet points, no headers, precise and insightful. \
Anchor every judgment in the numbers provided.\
"""

QUADRANT_SYSTEM_PROMPT = """\
You are a quant equity analyst. The user will give you a breakdown of the \
Goldman Sachs Hedge Industry VIP ETF holdings mapped onto a quadrant chart: \
X-axis is 3-month price momentum (rank Z-score), Y-axis is short interest \
decile (1=least shorted, 10=most shorted).

Write a focused commentary (STRICT maximum 300 words) highlighting 2-3 \
interesting names or clusters. Lead with squeeze candidates if any are notable. \
Call out any battleground names where shorts are fighting a VIP consensus long. \
Note clean longs with strong momentum and low opposition.

Style: flowing prose, no bullet points, no headers. Anchor every observation \
in the specific numbers provided.\
"""

# ── Fetch ─────────────────────────────────────────────────────────────────────

HEADERS = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"}


def fetch_holdings() -> list[dict]:
    resp = requests.get(HOLDINGS_URL, timeout=20, headers=HEADERS)
    resp.raise_for_status()
    soup = BeautifulSoup(resp.text, "html.parser")

    holdings = []
    for row in soup.find_all("tr"):
        cells = row.find_all("td")
        if len(cells) < 4:
            continue
        texts = [c.get_text(strip=True) for c in cells]
        try:
            rank = int(texts[0])
        except (ValueError, IndexError):
            continue
        ticker = texts[1].strip()
        name = texts[2].strip()
        weight_str = texts[3].replace("%", "").strip()
        shares_str = texts[4].replace(",", "").strip() if len(texts) > 4 else "0"
        try:
            weight = float(weight_str)
            shares = int(shares_str) if shares_str.isdigit() else 0
        except (ValueError, TypeError):
            continue
        holdings.append({
            "rank": rank,
            "ticker": ticker,
            "name": name,
            "weight": weight,
            "shares": shares,
        })

    print(f"  ✓ GVIP: {len(holdings)} holdings fetched")
    return holdings


def fetch_performance() -> dict:
    t = yf.Ticker(TICKER)
    info = t.info

    hist = t.history(period="1y")
    close = hist["Close"]
    now = float(close.iloc[-1])

    def ret(n_days):
        if len(close) > n_days:
            return round((now / float(close.iloc[-n_days]) - 1) * 100, 2)
        return None

    ytd_mask = close.index.year == date.today().year
    ytd_first = float(close[ytd_mask].iloc[0]) if ytd_mask.any() else float(close.iloc[0])

    return {
        "price": round(now, 2),
        "aum": info.get("totalAssets", 0),
        "ret_1m": ret(22),
        "ret_3m": ret(63),
        "ret_ytd": round((now / ytd_first - 1) * 100, 2),
        "ret_1y": ret(252),
        "week52_low": info.get("fiftyTwoWeekLow"),
        "week52_high": info.get("fiftyTwoWeekHigh"),
        "avg_volume": info.get("averageVolume"),
        "as_of": close.index[-1].strftime("%Y-%m-%d"),
    }


def fetch_sector_weights() -> dict:
    t = yf.Ticker(TICKER)
    fd = t.funds_data
    try:
        sw = fd.sector_weightings or {}
        return {k: round(v * 100, 2) for k, v in sw.items() if v > 0}
    except Exception:
        return {}


def fetch_price_history() -> dict:
    """Fetch 1Y history for GVIP and SPY, both indexed to 100 at the start."""
    tickers = yf.download([TICKER, "SPY"], period="1y", auto_adjust=True, progress=False)["Close"]
    tickers = tickers.dropna(how="all")
    base = tickers.iloc[0]
    indexed = (tickers / base * 100).round(2)
    dates = [str(d.date()) for d in indexed.index]
    return {
        "dates": dates,
        "gvip": [round(v, 2) if not __import__("math").isnan(v) else None for v in indexed[TICKER].tolist()],
        "spy":  [round(v, 2) if not __import__("math").isnan(v) else None for v in indexed["SPY"].tolist()],
    }


def fetch_holding_momentum(holdings: list[dict]) -> dict:
    """Fetch 3-month returns for each holding ticker. Returns {ticker: return_pct}."""
    import math
    tickers = [h["ticker"] for h in holdings]
    try:
        raw = yf.download(tickers, period="3mo", auto_adjust=True, progress=False)["Close"]
    except Exception:
        return {}
    if raw.empty:
        return {}
    result = {}
    for tk in tickers:
        try:
            col = raw[tk].dropna() if tk in raw.columns else raw.dropna()
            if len(col) < 2:
                continue
            ret = (float(col.iloc[-1]) / float(col.iloc[0]) - 1) * 100
            if not math.isnan(ret):
                result[tk] = round(ret, 2)
        except Exception:
            continue
    return result


def fetch_holding_fundamentals(tickers: list[str]) -> dict:
    """Fetch forwardPE and shortPercentOfFloat for each ticker in one batch.
    Returns {"pe": {tk: float|None}, "short": {tk: float|None}}."""
    pe, short = {}, {}
    try:
        batch = yf.Tickers(" ".join(tickers))
        for tk in tickers:
            try:
                info = batch.tickers[tk].info
                pe[tk] = info.get("forwardPE")
                si = info.get("shortPercentOfFloat")
                short[tk] = round(si * 100, 2) if si is not None else None
            except Exception:
                pe[tk] = None
                short[tk] = None
    except Exception:
        for tk in tickers:
            pe[tk] = None
            short[tk] = None
    return {"pe": pe, "short": short}


def fetch_mtum_holdings() -> dict:
    """Fetch MTUM holdings from iShares SpreadsheetML. Returns {ticker: weight_pct}."""
    from lxml import etree
    url = (
        "https://www.ishares.com/us/products/251614/ishares-msci-usa-momentum-factor-etf/"
        "1521942788811.ajax?fileType=xls&fileName=iShares-MSCI-USA-Momentum-Factor-ETF_fund&dataType=fund"
    )
    resp = requests.get(url, timeout=30, headers=HEADERS)
    resp.raise_for_status()
    content = resp.content.lstrip(b"\xef\xbb\xbf")
    root = etree.fromstring(content, etree.XMLParser(recover=True))
    ns = {"ss": "urn:schemas-microsoft-com:office:spreadsheet"}
    worksheets = root.findall(".//ss:Worksheet", ns)
    holdings_ws = next(
        (w for w in worksheets
         if w.get("{urn:schemas-microsoft-com:office:spreadsheet}Name") == "Holdings"),
        worksheets[1] if len(worksheets) > 1 else None,
    )
    if holdings_ws is None:
        print("  ⚠ MTUM: Holdings worksheet not found", file=sys.stderr)
        return {}
    rows = holdings_ws.find("ss:Table", ns).findall("ss:Row", ns)
    ticker_col = weight_col = data_start = None
    for i, row in enumerate(rows):
        texts = [
            (c.find("ss:Data", ns).text or "").strip()
            for c in row.findall("ss:Cell", ns)
            if c.find("ss:Data", ns) is not None
        ]
        if "Ticker" in texts:
            ticker_col = texts.index("Ticker")
            weight_col = next((j for j, t in enumerate(texts) if "Weight" in t), None)
            data_start = i + 1
            break
    if ticker_col is None or weight_col is None:
        print("  ⚠ MTUM: header row not found", file=sys.stderr)
        return {}
    result = {}
    for row in rows[data_start:]:
        texts = [
            (c.find("ss:Data", ns).text or "").strip()
            for c in row.findall("ss:Cell", ns)
            if c.find("ss:Data", ns) is not None
        ]
        if len(texts) <= max(ticker_col, weight_col):
            continue
        tk = texts[ticker_col]
        if not tk or tk.lower() in ("", "nan", "-"):
            continue
        try:
            w = float(texts[weight_col])
            if w > 0:
                result[tk] = round(w, 4)
        except (ValueError, TypeError):
            continue
    print(f"  ✓ MTUM: {len(result)} holdings fetched")
    return result

# ── Cache ─────────────────────────────────────────────────────────────────────

def snapshot_path(d: str) -> Path:
    return CACHE_DIR / f"{d}.json"


def save_snapshot(data: dict, today: str):
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    path = snapshot_path(today)
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
    print(f"  Saved snapshot: {path.name}")
    prune_snapshots()


def prune_snapshots():
    files = sorted(CACHE_DIR.glob("*.json"))
    while len(files) > MAX_SNAPSHOTS:
        files[0].unlink()
        print(f"  Pruned old snapshot: {files[0].name}")
        files = files[1:]


def load_snapshots() -> list[dict]:
    files = sorted(CACHE_DIR.glob("*.json"))
    snapshots = []
    for f in files:
        with open(f) as fh:
            snapshots.append(json.load(fh))
    return snapshots


def latest_snapshot_before(today: str) -> dict | None:
    files = sorted(CACHE_DIR.glob("*.json"))
    candidates = [f for f in files if f.stem < today]
    if not candidates:
        return None
    with open(candidates[-1]) as fh:
        return json.load(fh)


def snapshot_two_weeks_ago(today: str) -> dict | None:
    """Return cached snapshot closest to today - 14 days (falls back to oldest available)."""
    files = sorted(CACHE_DIR.glob("*.json"))
    candidates = [f for f in files if f.stem < today]
    if not candidates:
        return None
    target = datetime.strptime(today, "%Y-%m-%d") - timedelta(days=14)
    best = min(candidates, key=lambda f: abs(
        (datetime.strptime(f.stem, "%Y-%m-%d") - target).days
    ))
    with open(best) as fh:
        return json.load(fh)

# ── Diffs ─────────────────────────────────────────────────────────────────────

def compute_diff(today_h: list[dict], prior_h: list[dict]) -> dict:
    today_map = {h["ticker"]: h for h in today_h}
    prior_map = {h["ticker"]: h for h in prior_h}

    new_pos = [today_map[t] for t in today_map if t not in prior_map]
    removed = [prior_map[t] for t in prior_map if t not in today_map]
    changed = []
    for tk in today_map:
        if tk in prior_map:
            delta = today_map[tk]["weight"] - prior_map[tk]["weight"]
            if abs(delta) >= 0.5:
                changed.append({
                    "ticker": tk,
                    "name": today_map[tk]["name"],
                    "today": today_map[tk]["weight"],
                    "prior": prior_map[tk]["weight"],
                    "delta": delta,
                })

    return {"new": new_pos, "removed": removed, "changed": changed}

# ── Context / Commentary ──────────────────────────────────────────────────────

def build_context(today_data: dict, diff: dict) -> str:
    perf = today_data["performance"]
    holdings = today_data["holdings"]
    sectors = today_data["sectors"]

    lines = [
        f"Date: {today_data['date']}",
        f"AUM: ${perf['aum']/1e6:.1f}M | Price: ${perf['price']:.2f}",
        "Returns: " + "  ".join(
            f"{label} {(v):+.2f}%" if v is not None else f"{label} n/a"
            for label, v in [("1M", perf["ret_1m"]), ("3M", perf["ret_3m"]),
                              ("YTD", perf["ret_ytd"]), ("1Y", perf["ret_1y"])]
        ),
        "",
        "Top 15 Holdings (by weight):",
    ]
    for h in holdings[:15]:
        lines.append(f"  {h['ticker']:8s}  {h['weight']:+.2f}%  {h['name']}")

    lines.append("")
    lines.append("Sector Allocation:")
    for sector, pct in sorted(sectors.items(), key=lambda x: -x[1]):
        label = SECTOR_LABELS.get(sector, sector)
        lines.append(f"  {label}: {pct:.1f}%")

    if diff.get("new"):
        lines.append("")
        lines.append("New positions: " + ", ".join(f"{h['ticker']} ({h['weight']:+.1f}%)" for h in diff["new"]))
    if diff.get("removed"):
        lines.append("Removed: " + ", ".join(h["ticker"] for h in diff["removed"]))
    if diff.get("changed"):
        lines.append("Weight changes: " + ", ".join(
            f"{c['ticker']} {c['prior']:.1f}%→{c['today']:.1f}% ({c['delta']:+.1f}%)"
            for c in sorted(diff["changed"], key=lambda x: -abs(x["delta"]))[:8]
        ))

    return "\n".join(lines)


def print_context_for_claude(today_data: dict, diff: dict, prior_date: str | None):
    context_text = build_context(today_data, diff)
    out = {
        "date": today_data["date"],
        "prior_date": prior_date,
        "context_text": context_text,
        "instruction": (
            "You are a macro and equity analyst. Write a concise commentary (max 400 words) "
            "on the current positioning of the Goldman Sachs Hedge Industry VIP ETF (GVIP). "
            "Cover: what the VIP basket is expressing about hedge fund conviction, key sector "
            "tilts, notable position changes, and macro/earnings implications. "
            "Open with a 'Key themes' paragraph (2-3 sentences). "
            "Prose only — no bullet points, no headers."
        ),
    }
    print(json.dumps(out, indent=2))


def load_summary_meta() -> dict:
    if SUMMARY_META_FILE.exists():
        try:
            return json.loads(SUMMARY_META_FILE.read_text())
        except Exception:
            pass
    return {}


def save_summary_meta(generated_at: str, word_count: int):
    SUMMARY_META_FILE.parent.mkdir(parents=True, exist_ok=True)
    SUMMARY_META_FILE.write_text(json.dumps({
        "generated_at": generated_at,
        "word_count": word_count,
    }, indent=2))


def should_refresh_summary() -> bool:
    meta = load_summary_meta()
    if not meta.get("generated_at"):
        return True
    try:
        last = datetime.strptime(meta["generated_at"][:10], "%Y-%m-%d").date()
        return (date.today() - last).days >= SUMMARY_REFRESH_DAYS
    except Exception:
        return True


def generate_summary_gemma(context_text: str, hf_token: str, retries: int = 5) -> str:
    client = InferenceClient(model=MODEL_ID, token=hf_token, timeout=300)
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": (
            "Please analyse the following GVIP positioning snapshot and write your commentary:\n\n"
            + context_text
        )},
    ]
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                messages=messages,
                temperature=0.3,
                max_tokens=600,
                stream=False,
            )
            text = response.choices[0].message.content or ""
            if not text.strip():
                raise ValueError("Gemma returned empty response")
            return text.strip()
        except Exception as e:
            is_rate_limit = "429" in str(e) or "Too Many Requests" in str(e)
            if attempt < retries - 1:
                wait = 60 * (attempt + 1) if is_rate_limit else 10
                print(f"  Gemma attempt {attempt+1}/{retries} failed ({e}), retrying in {wait}s...",
                      file=sys.stderr)
                time.sleep(wait)
            else:
                raise


def extract_existing_summary() -> str:
    out_path = REPORT_DIR / "index.html"
    if not out_path.exists():
        return ""
    html = out_path.read_text()
    m = re.search(r'<div class="summary-box">(.*?)</div>', html, re.DOTALL)
    if not m:
        return ""
    return m.group(1).replace("<br>", "\n").strip()


def extract_existing_quadrant_commentary() -> str:
    out_path = REPORT_DIR / "index.html"
    if not out_path.exists():
        return ""
    html = out_path.read_text()
    m = re.search(r'<div class="quadrant-commentary-box">(.*?)</div>', html, re.DOTALL)
    if not m:
        return ""
    return m.group(1).replace("<br>", "\n").strip()


def load_quadrant_meta() -> dict:
    if QUADRANT_META_FILE.exists():
        try:
            return json.loads(QUADRANT_META_FILE.read_text())
        except Exception:
            pass
    return {}


def save_quadrant_meta(generated_at: str, word_count: int):
    QUADRANT_META_FILE.parent.mkdir(parents=True, exist_ok=True)
    QUADRANT_META_FILE.write_text(json.dumps({
        "generated_at": generated_at,
        "word_count": word_count,
    }, indent=2))


def should_refresh_quadrant_commentary() -> bool:
    meta = load_quadrant_meta()
    if not meta.get("generated_at"):
        return True
    try:
        last = datetime.strptime(meta["generated_at"][:10], "%Y-%m-%d").date()
        return (date.today() - last).days >= SUMMARY_REFRESH_DAYS
    except Exception:
        return True


def build_quadrant_context(holdings: list[dict], momentum: dict, fundamentals: dict) -> str:
    short_data = fundamentals.get("short", {})
    pe_data = fundamentals.get("pe", {})

    pts = [(h["ticker"], h["name"], h["weight"], momentum.get(h["ticker"]))
           for h in holdings if h["ticker"] in momentum]

    shorts = [short_data.get(p[0]) for p in pts]
    valid_si = [(i, v) for i, v in enumerate(shorts) if v is not None]
    valid_si_sorted = sorted(valid_si, key=lambda x: x[1])
    n_si = len(valid_si_sorted)
    idx_to_si_decile = {i: min(10, int(rank * 10 / n_si) + 1)
                        for rank, (i, _) in enumerate(valid_si_sorted)}

    import statistics as _st
    returns = [p[3] for p in pts]
    order = sorted(range(len(returns)), key=lambda i: returns[i])
    ranks = [0] * len(returns)
    for r, i in enumerate(order):
        ranks[i] = r + 1
    m, s = _st.mean(ranks), _st.stdev(ranks) or 1
    zx = [(r - m) / s for r in ranks]

    quadrants = {"Squeeze Candidates": [], "Battleground": [],
                 "Clean Longs": [], "Quiet Laggards": []}
    for i, (tk, nm, wt, ret) in enumerate(pts):
        si_d = idx_to_si_decile.get(i, 5)
        si_pct = shorts[i]
        pe = pe_data.get(tk)
        high_mom = zx[i] > 0
        high_si = si_d > 5
        label = ("Squeeze Candidates" if high_mom and high_si else
                 "Battleground" if not high_mom and high_si else
                 "Clean Longs" if high_mom and not high_si else
                 "Quiet Laggards")
        pe_str = f"fwd P/E {pe:.1f}" if pe else "P/E n/a"
        quadrants[label].append(
            f"{tk} ({nm}): 3M mom {ret:+.1f}%, SI decile {si_d} ({si_pct:.1f}% float), {pe_str}, weight {wt:.2f}%"
        )

    lines = ["GVIP Quadrant Positioning:"]
    for q, items in quadrants.items():
        lines.append(f"\n{q} ({len(items)} names):")
        lines.extend(f"  {item}" for item in items)
    return "\n".join(lines)


def generate_quadrant_commentary_gemma(context: str, hf_token: str, retries: int = 5) -> str:
    client = InferenceClient(model=MODEL_ID, token=hf_token, timeout=300)
    messages = [
        {"role": "system", "content": QUADRANT_SYSTEM_PROMPT},
        {"role": "user", "content": "Analyse this quadrant positioning and write your commentary:\n\n" + context},
    ]
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                messages=messages, temperature=0.3, max_tokens=450, stream=False,
            )
            text = response.choices[0].message.content or ""
            if not text.strip():
                raise ValueError("Empty response")
            return text.strip()
        except Exception as e:
            is_rate_limit = "429" in str(e) or "Too Many Requests" in str(e)
            if attempt < retries - 1:
                wait = 60 * (attempt + 1) if is_rate_limit else 10
                print(f"  Gemma quadrant attempt {attempt+1}/{retries} failed ({e}), retrying in {wait}s...",
                      file=sys.stderr)
                time.sleep(wait)
            else:
                raise

# ── HTML ──────────────────────────────────────────────────────────────────────

def fmt_ret(val: float | None, with_sign: bool = True) -> tuple[str, str]:
    if val is None:
        return "n/a", "#6b7280"
    sign = "+" if (with_sign and val >= 0) else ""
    color = "#16a34a" if val >= 0 else "#dc2626"
    return f"{sign}{val:.2f}%", color


def price_chart_js(price_history: dict) -> str:
    labels_json = json.dumps(price_history["dates"])
    gvip_json   = json.dumps(price_history["gvip"])
    spy_json    = json.dumps(price_history["spy"])
    return f"""
<div style="max-width:900px;margin:0 auto 2rem;">
  <canvas id="priceChart" height="100"></canvas>
</div>
<script>
new Chart(document.getElementById('priceChart'), {{
  type: 'line',
  data: {{
    labels: {labels_json},
    datasets: [
      {{
        label: 'GVIP',
        data: {gvip_json},
        borderColor: '#1a56db',
        backgroundColor: 'rgba(26,86,219,0.08)',
        tension: 0.3,
        fill: false,
        pointRadius: 0,
        borderWidth: 2.5,
        spanGaps: true,
      }},
      {{
        label: 'SPY',
        data: {spy_json},
        borderColor: '#94a3b8',
        backgroundColor: 'transparent',
        tension: 0.3,
        fill: false,
        pointRadius: 0,
        borderWidth: 1.5,
        borderDash: [4, 3],
        spanGaps: true,
      }}
    ]
  }},
  options: {{
    responsive: true,
    interaction: {{ mode: 'index', intersect: false }},
    plugins: {{
      legend: {{ position: 'top', labels: {{ font: {{ size: 12 }} }} }},
      tooltip: {{
        callbacks: {{
          label: function(ctx) {{
            return ' ' + ctx.dataset.label + ': ' + ctx.parsed.y.toFixed(1);
          }}
        }}
      }}
    }},
    scales: {{
      y: {{ title: {{ display: true, text: 'Indexed (base = 100)' }}, grid: {{ color: '#f3f4f6' }} }},
      x: {{ grid: {{ color: '#f3f4f6' }}, ticks: {{ maxTicksLimit: 10 }} }}
    }}
  }}
}});
</script>"""


def quadrant_chart_js(holdings: list[dict], momentum: dict, fundamentals: dict) -> str:
    import math, statistics

    pe_data = fundamentals.get("pe", {})
    short_data = fundamentals.get("short", {})

    pts = [(h["ticker"], h["name"], h["weight"], momentum[h["ticker"]])
           for h in holdings if h["ticker"] in momentum]
    if len(pts) < 3:
        return '<p style="color:#6b7280;font-style:italic">Insufficient momentum data for quadrant chart.</p>'

    tickers = [p[0] for p in pts]
    names   = [p[1] for p in pts]
    weights = [p[2] for p in pts]
    returns = [p[3] for p in pts]
    shorts  = [short_data.get(tk) for tk in tickers]

    def rank_zscore(vals):
        """Rank-based Z-scores: forces uniform spread regardless of distribution."""
        order = sorted(range(len(vals)), key=lambda i: vals[i])
        ranks = [0] * len(vals)
        for r, i in enumerate(order):
            ranks[i] = r + 1
        m = statistics.mean(ranks)
        s = statistics.stdev(ranks) or 1
        return [(r - m) / s for r in ranks]

    zx = rank_zscore(returns)
    valid_shorts = [v for v in shorts if v is not None]

    # assign short interest deciles 1–10
    si_with_idx = sorted([(i, v) for i, v in enumerate(shorts) if v is not None], key=lambda x: x[1])
    n_si = len(si_with_idx)
    idx_to_si_decile = {i: min(10, int(rank * 10 / n_si) + 1) for rank, (i, _) in enumerate(si_with_idx)}
    zy = [idx_to_si_decile.get(i, 5) for i in range(len(shorts))]
    si_cap = None  # no winsorization needed

    # P/E color: assign deciles 1–10 across valid PEs, gray for missing
    pe_vals = [pe_data.get(tk) for tk in tickers]
    valid_with_idx = [(i, pe_vals[i]) for i in range(len(pe_vals))
                      if pe_vals[i] is not None and not math.isnan(pe_vals[i])]
    valid_with_idx.sort(key=lambda x: x[1])
    n_valid = len(valid_with_idx)
    idx_to_decile = {
        i: min(10, int(rank * 10 / n_valid) + 1)
        for rank, (i, _) in enumerate(valid_with_idx)
    }

    def decile_color(d):
        norm = (d - 1) / 9.0  # 0 (cheapest) → 1 (priciest)
        if norm < 0.5:
            return f"rgb({int(norm * 2 * 220)},200,60)"
        else:
            return f"rgb(220,{int((1 - norm) * 2 * 200)},60)"

    colors = [
        decile_color(idx_to_decile[i]) if i in idx_to_decile else "#9ca3af"
        for i in range(len(pe_vals))
    ]
    deciles = [idx_to_decile.get(i) for i in range(len(pe_vals))]

    def si_label(si):
        if si is None:
            return "n/a"
        clipped = si_cap is not None and si > si_cap
        return f"{si:.1f}%{'*' if clipped else ''}"

    hover = [
        f"<b>{tk}</b><br>{nm}<br>Momentum (3M): {ret:+.1f}%<br>"
        f"Short % Float: {si_label(si)}<br>"
        f"Fwd P/E: {f'{pe:.1f} (D{d})' if pe is not None and not math.isnan(pe) else 'n/a'}<extra></extra>"
        for tk, nm, wt, ret, si, pe, d in zip(tickers, names, weights, returns, shorts, pe_vals, deciles)
    ]

    axis_pad = 2.2
    si_mid = 5.5  # decile midpoint crosshair
    si_max = 10.5
    si_min = 0.5
    max_weight = max(weights) if weights else 1
    sizes = [6 + (w / max_weight) * 14 for w in weights]

    trace = {
        "type": "scatter",
        "mode": "markers+text",
        "x": zx,
        "y": zy,
        "text": tickers,
        "textposition": "top center",
        "textfont": {"size": 9, "color": "#374151"},
        "hovertemplate": hover,
        "marker": {
            "size": sizes,
            "sizemode": "diameter",
            "color": colors,
            "opacity": 0.85,
            "line": {"width": 1.5, "color": "#fff"},
        },
    }

    layout = {
        "paper_bgcolor": "#fff",
        "plot_bgcolor": "#f8fafc",
        "margin": {"l": 60, "r": 40, "t": 30, "b": 60},
        "height": 560,
        "xaxis": {
            "title": "Relative Momentum (Z-Score)",
            "zeroline": False,
            "range": [-axis_pad, axis_pad],
            "gridcolor": "#e5e7eb",
        },
        "yaxis": {
            "title": "Short Interest Decile (1 = lowest, 10 = highest)",
            "zeroline": False,
            "range": [si_min, si_max],
            "tickvals": list(range(1, 11)),
            "gridcolor": "#e5e7eb",
        },
        "shapes": [
            {"type": "line", "x0": -axis_pad, "x1": axis_pad,
             "y0": si_mid, "y1": si_mid,
             "line": {"color": "#9ca3af", "width": 1, "dash": "dash"}},
            {"type": "line", "x0": 0, "x1": 0, "y0": si_min, "y1": si_max,
             "line": {"color": "#9ca3af", "width": 1, "dash": "dash"}},
        ],
        "annotations": [
            {"x": axis_pad - 0.05, "y": 10.2, "xanchor": "right", "yanchor": "top",
             "text": "Squeeze Candidates", "showarrow": False,
             "font": {"size": 10, "color": "#6b7280"}, "bgcolor": "rgba(255,255,255,0.7)"},
            {"x": -axis_pad + 0.05, "y": 10.2, "xanchor": "left", "yanchor": "top",
             "text": "Battleground", "showarrow": False,
             "font": {"size": 10, "color": "#6b7280"}, "bgcolor": "rgba(255,255,255,0.7)"},
            {"x": axis_pad - 0.05, "y": 0.8, "xanchor": "right", "yanchor": "bottom",
             "text": "Clean Longs", "showarrow": False,
             "font": {"size": 10, "color": "#6b7280"}, "bgcolor": "rgba(255,255,255,0.7)"},
            {"x": -axis_pad + 0.05, "y": 0.8, "xanchor": "left", "yanchor": "bottom",
             "text": "Quiet Laggards", "showarrow": False,
             "font": {"size": 10, "color": "#6b7280"}, "bgcolor": "rgba(255,255,255,0.7)"},
        ],
    }

    pe_legend = (
        '<p style="font-size:0.78rem;color:#6b7280;text-align:center;margin-top:-1rem;margin-bottom:1rem">'
        'Dot color = forward P/E decile &nbsp;|&nbsp; '
        '<span style="display:inline-block;width:10px;height:10px;background:rgb(0,200,60);border-radius:50%;vertical-align:middle"></span> D1 cheapest '
        '&nbsp;→&nbsp; '
        '<span style="display:inline-block;width:10px;height:10px;background:rgb(220,0,60);border-radius:50%;vertical-align:middle"></span> D10 priciest '
        '&nbsp;|&nbsp; <span style="color:#9ca3af">●</span> n/a'
        '&nbsp;|&nbsp; Bubble size = ETF weight %'
        '</p>'
    )

    return f"""
<div id="quadrantChart" style="max-width:700px;margin:0 auto 1rem;"></div>
{pe_legend}
<script>
Plotly.newPlot('quadrantChart', [{json.dumps(trace)}], {json.dumps(layout)}, {{responsive: true, displayModeBar: false}});
</script>"""


def sector_chart_js(sectors: dict) -> str:
    sorted_s = sorted(sectors.items(), key=lambda x: x[1])
    labels = [SECTOR_LABELS.get(s, s) for s, _ in sorted_s]
    data = [pct for _, pct in sorted_s]
    colors = [SECTOR_COLORS.get(s, "#6b7280") + "cc" for s, _ in sorted_s]
    borders = [SECTOR_COLORS.get(s, "#6b7280") for s, _ in sorted_s]
    n = len(labels)
    height = max(160, n * 30)

    return f"""
<div style="max-width:700px;margin:0 auto 2rem;">
  <div style="position:relative;height:{height}px">
    <canvas id="sectorChart"></canvas>
  </div>
</div>
<script>
(function() {{
  new Chart(document.getElementById('sectorChart'), {{
    type: 'bar',
    data: {{
      labels: {json.dumps(labels)},
      datasets: [{{
        label: 'Weight (%)',
        data: {json.dumps(data)},
        backgroundColor: {json.dumps(colors)},
        borderColor: {json.dumps(borders)},
        borderWidth: 1,
        borderRadius: 3,
      }}]
    }},
    options: {{
      indexAxis: 'y',
      responsive: true,
      maintainAspectRatio: false,
      plugins: {{ legend: {{ display: false }} }},
      scales: {{
        x: {{ title: {{ display: true, text: 'Weight (%)' }}, grid: {{ color: '#f3f4f6' }} }},
        y: {{ ticks: {{ font: {{ family: 'monospace', size: 11 }} }} }}
      }}
    }}
  }});
}})();
</script>"""


def relative_positioning_chart_js(gvip_holdings: list[dict], mtum_holdings: dict, fundamentals: dict) -> str:
    import math
    if not mtum_holdings:
        return '<p style="color:#6b7280;font-style:italic">MTUM holdings unavailable — chart skipped.</p>'
    gvip_map = {h["ticker"]: h for h in gvip_holdings}
    common = sorted(set(gvip_map) & set(mtum_holdings))
    if not common:
        return '<p style="color:#6b7280;font-style:italic">No overlapping tickers between GVIP and MTUM.</p>'
    tickers = common
    names   = [gvip_map[tk]["name"] for tk in tickers]
    gvip_w  = [gvip_map[tk]["weight"] for tk in tickers]
    mtum_w  = [mtum_holdings[tk] for tk in tickers]

    # P/E decile coloring — same methodology as quadrant chart
    pe_data = fundamentals.get("pe", {})
    pe_vals = [pe_data.get(tk) for tk in tickers]
    valid_with_idx = sorted(
        [(i, v) for i, v in enumerate(pe_vals) if v is not None and not math.isnan(v)],
        key=lambda x: x[1],
    )
    n_valid = len(valid_with_idx)
    idx_to_decile = {
        i: min(10, int(rank * 10 / n_valid) + 1)
        for rank, (i, _) in enumerate(valid_with_idx)
    }

    def decile_color(d):
        norm = (d - 1) / 9.0
        return (f"rgb({int(norm * 2 * 220)},200,60)" if norm < 0.5
                else f"rgb(220,{int((1 - norm) * 2 * 200)},60)")

    colors  = [decile_color(idx_to_decile[i]) if i in idx_to_decile else "#9ca3af" for i in range(len(pe_vals))]
    deciles = [idx_to_decile.get(i) for i in range(len(pe_vals))]

    max_gvip = max(gvip_w) if gvip_w else 1
    sizes = [6 + (w / max_gvip) * 14 for w in gvip_w]

    hover = [
        f"<b>{tk}</b><br>{nm}<br>GVIP: {gw:.2f}%<br>MTUM: {mw:.4f}%<br>"
        f"Fwd P/E: {f'{pe:.1f} (D{d})' if pe is not None and not math.isnan(pe) else 'n/a'}<extra></extra>"
        for tk, nm, gw, mw, pe, d in zip(tickers, names, gvip_w, mtum_w, pe_vals, deciles)
    ]

    x_max  = max(gvip_w) * 1.18
    y_max  = max(mtum_w) * 1.18
    x_mid  = sum(gvip_w) / len(gvip_w)
    y_mid  = sum(mtum_w) / len(mtum_w)

    trace = {
        "type": "scatter",
        "mode": "markers+text",
        "x": gvip_w,
        "y": mtum_w,
        "text": tickers,
        "textposition": "top center",
        "textfont": {"size": 9, "color": "#374151"},
        "hovertemplate": hover,
        "marker": {
            "size": sizes,
            "sizemode": "diameter",
            "color": colors,
            "opacity": 0.85,
            "line": {"width": 1.5, "color": "#fff"},
        },
    }
    layout = {
        "paper_bgcolor": "#fff",
        "plot_bgcolor": "#f8fafc",
        "margin": {"l": 70, "r": 40, "t": 30, "b": 70},
        "height": 520,
        "xaxis": {"title": "GVIP Weight (%)", "gridcolor": "#e5e7eb", "zeroline": False, "range": [0, x_max]},
        "yaxis": {"title": "MTUM Weight (%)", "gridcolor": "#e5e7eb", "zeroline": False, "range": [0, y_max]},
        "shapes": [
            {"type": "line", "x0": x_mid, "x1": x_mid, "y0": 0, "y1": y_max,
             "line": {"color": "#9ca3af", "width": 1, "dash": "dash"}},
            {"type": "line", "x0": 0, "x1": x_max, "y0": y_mid, "y1": y_mid,
             "line": {"color": "#9ca3af", "width": 1, "dash": "dash"}},
        ],
        "annotations": [
            {"x": x_max * 0.97, "y": y_max * 0.97, "xanchor": "right", "yanchor": "top",
             "text": "Shared Conviction", "showarrow": False,
             "font": {"size": 10, "color": "#6b7280"}, "bgcolor": "rgba(255,255,255,0.7)"},
            {"x": x_max * 0.03, "y": y_max * 0.97, "xanchor": "left", "yanchor": "top",
             "text": "Momentum Driven", "showarrow": False,
             "font": {"size": 10, "color": "#6b7280"}, "bgcolor": "rgba(255,255,255,0.7)"},
            {"x": x_max * 0.97, "y": y_max * 0.03, "xanchor": "right", "yanchor": "bottom",
             "text": "VIP Only", "showarrow": False,
             "font": {"size": 10, "color": "#6b7280"}, "bgcolor": "rgba(255,255,255,0.7)"},
            {"x": x_max * 0.03, "y": y_max * 0.03, "xanchor": "left", "yanchor": "bottom",
             "text": "Peripheral", "showarrow": False,
             "font": {"size": 10, "color": "#6b7280"}, "bgcolor": "rgba(255,255,255,0.7)"},
        ],
    }
    pe_legend = (
        '<p style="font-size:0.78rem;color:#6b7280;text-align:center;margin-top:-1rem;margin-bottom:1rem">'
        'Dot color = forward P/E decile &nbsp;|&nbsp; '
        '<span style="display:inline-block;width:10px;height:10px;background:rgb(0,200,60);border-radius:50%;vertical-align:middle"></span> D1 cheapest '
        '&nbsp;→&nbsp; '
        '<span style="display:inline-block;width:10px;height:10px;background:rgb(220,0,60);border-radius:50%;vertical-align:middle"></span> D10 priciest '
        '&nbsp;|&nbsp; <span style="color:#9ca3af">●</span> n/a'
        '&nbsp;|&nbsp; Bubble size = GVIP weight %'
        '</p>'
    )
    caption = (
        f'<p style="font-size:0.78rem;color:#6b7280;text-align:center;margin-top:-0.5rem;margin-bottom:0">'
        f'{len(common)} tickers in both GVIP &amp; MTUM &nbsp;|&nbsp; dividers at mean weight</p>'
    )
    return f"""
<div id="relPositChart" style="max-width:700px;margin:0 auto 1rem;"></div>
{caption}
{pe_legend}
<script>
Plotly.newPlot('relPositChart', [{json.dumps(trace)}], {json.dumps(layout)}, {{responsive: true, displayModeBar: false}});
</script>"""


def holdings_table_html(holdings: list[dict]) -> str:
    rows = []
    for h in holdings:
        w = h["weight"]
        color = "#16a34a" if w > 0 else "#dc2626"
        rows.append(
            f'<tr>'
            f'<td style="color:#6b7280;text-align:center">{h["rank"]}</td>'
            f'<td style="font-family:monospace;font-weight:600">{h["ticker"]}</td>'
            f'<td>{h["name"]}</td>'
            f'<td style="text-align:right">{h["shares"]:,}</td>'
            f'<td style="text-align:right;color:{color};font-weight:600">+{w:.2f}%</td>'
            f'</tr>'
        )
    return (
        '<div style="overflow-x:auto"><table class="htable">'
        '<thead><tr>'
        '<th style="text-align:center">#</th>'
        '<th>Ticker</th><th>Company</th>'
        '<th style="text-align:right">Shares</th>'
        '<th style="text-align:right">Weight</th>'
        '</tr></thead>'
        f'<tbody>{"".join(rows)}</tbody>'
        '</table></div>'
    )


def change_log_html(diff: dict, prior_date: str | None) -> str:
    if not prior_date:
        return '<p style="color:#6b7280;font-style:italic">First snapshot — no prior data to compare.</p>'

    rows = []
    for h in diff.get("new", []):
        rows.append(f'<tr><td style="color:#16a34a">New</td><td style="font-family:monospace">{h["ticker"]}</td><td>{h["name"]}</td><td style="text-align:right;color:#16a34a">+{h["weight"]:.2f}%</td></tr>')
    for h in diff.get("removed", []):
        rows.append(f'<tr><td style="color:#dc2626">Removed</td><td style="font-family:monospace">{h["ticker"]}</td><td>{h["name"]}</td><td style="text-align:right;color:#dc2626">—</td></tr>')
    for c in sorted(diff.get("changed", []), key=lambda x: -abs(x["delta"])):
        sign = "+" if c["delta"] > 0 else ""
        color = "#16a34a" if c["delta"] > 0 else "#dc2626"
        rows.append(f'<tr><td style="color:{color}">Changed</td><td style="font-family:monospace">{c["ticker"]}</td><td>{c["name"]}</td><td style="text-align:right;color:{color}">{sign}{c["delta"]:.2f}%</td></tr>')

    if not rows:
        return f'<p style="color:#6b7280;font-style:italic">No significant changes vs prior snapshot ({prior_date}).</p>'

    return (
        f'<p style="color:#6b7280;font-size:0.85rem">vs {prior_date}</p>'
        '<div style="overflow-x:auto"><table class="htable">'
        '<thead><tr><th>Change</th><th>Ticker</th><th>Company</th><th style="text-align:right">Δ Weight</th></tr></thead>'
        f'<tbody>{"".join(rows)}</tbody></table></div>'
    )


def render_html(today_data: dict, diff: dict, summary: str,
                snapshots: list[dict], prior_date: str | None,
                price_history: dict, momentum: dict, fundamentals: dict,
                quadrant_commentary: str = "",
                generated_at: str | None = None,
                mtum_holdings: dict | None = None) -> str:
    today = today_data["date"]
    perf = today_data["performance"]
    sectors = today_data["sectors"]
    holdings = today_data["holdings"]

    aum_m = perf["aum"] / 1e6
    ret_1m, c1m = fmt_ret(perf["ret_1m"])
    ret_3m, c3m = fmt_ret(perf["ret_3m"])
    ret_ytd, cytd = fmt_ret(perf["ret_ytd"])
    ret_1y, c1y = fmt_ret(perf["ret_1y"])

    refresh_tag = (
        f'<p style="font-size:0.78rem;color:#9ca3af;margin-bottom:0.75rem">Last refreshed: {generated_at}</p>'
        if generated_at else ""
    )
    if summary:
        summary_html = (
            f'{refresh_tag}'
            f'<div class="summary-box">{summary.replace(chr(10), "<br>")}</div>'
        )
    else:
        summary_html = (
            '<p style="color:#6b7280;font-size:0.85rem;font-style:italic">'
            'Analyst commentary is generated when running the script locally with HF_TOKEN set.</p>'
        )

    week52_bar = ""
    if perf.get("week52_low") and perf.get("week52_high"):
        lo, hi, pr = perf["week52_low"], perf["week52_high"], perf["price"]
        pct = (pr - lo) / (hi - lo) * 100 if hi > lo else 50
        week52_bar = f"""
<div style="margin:1.5rem 0;">
  <div style="font-size:0.8rem;color:#6b7280;margin-bottom:0.3rem">52-Week Range</div>
  <div style="display:flex;align-items:center;gap:0.75rem;font-size:0.85rem">
    <span style="color:#6b7280">${lo:.2f}</span>
    <div style="flex:1;background:#e5e7eb;border-radius:4px;height:6px;position:relative">
      <div style="width:{pct:.1f}%;background:#1a56db;border-radius:4px;height:6px"></div>
    </div>
    <span style="color:#6b7280">${hi:.2f}</span>
  </div>
</div>"""

    holdings_html = holdings_table_html(holdings)
    change_html = change_log_html(diff, prior_date)
    p_chart  = price_chart_js(price_history)
    q_chart  = quadrant_chart_js(holdings, momentum, fundamentals)
    rp_chart = relative_positioning_chart_js(holdings, mtum_holdings or {}, fundamentals)
    s_chart  = sector_chart_js(sectors)

    holdings_as_of = today_data.get("holdings_as_of", today)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>GVIP — Goldman Sachs Hedge Industry VIP ETF</title>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
  <script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f8fafc; color: #0f172a; line-height: 1.6; }}
    .container {{ max-width: 1100px; margin: 0 auto; padding: 2rem 1.5rem; }}
    .fund-header {{ background: linear-gradient(135deg, #0f172a 0%, #1e3a5f 100%); color: #fff; border-radius: 12px; padding: 2rem; margin-bottom: 2rem; }}
    .fund-header h1 {{ font-size: 1.6rem; font-weight: 800; margin-bottom: 0.25rem; }}
    .fund-header .ticker {{ font-size: 1rem; color: #93c5fd; font-weight: 700; letter-spacing: 0.05em; }}
    .fund-header .objective {{ font-size: 0.85rem; color: #cbd5e1; margin-top: 0.75rem; max-width: 700px; line-height: 1.5; }}
    .perf-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(130px, 1fr)); gap: 0.75rem; margin: 1.5rem 0 0; }}
    .perf-card {{ background: rgba(255,255,255,0.1); border-radius: 8px; padding: 0.75rem 1rem; }}
    .perf-card .label {{ font-size: 0.72rem; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em; }}
    .perf-card .value {{ font-size: 1.3rem; font-weight: 800; margin-top: 0.1rem; }}
    .meta-bar {{ display: flex; gap: 2rem; flex-wrap: wrap; margin-top: 1rem; font-size: 0.82rem; color: #94a3b8; }}
    .meta-bar span b {{ color: #e2e8f0; }}
    h2 {{ font-size: 1.15rem; font-weight: 700; margin: 2rem 0 0.75rem; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.4rem; color: #0f172a; }}
    .summary-box {{ background: #fff; border: 1px solid #e2e8f0; border-left: 4px solid #1a56db; border-radius: 8px; padding: 1.5rem; font-size: 0.95rem; line-height: 1.85; color: #1e293b; }}
    .quadrant-commentary-box {{ background: #f8fafc; border: 1px solid #e2e8f0; border-left: 4px solid #7c3aed; border-radius: 8px; padding: 1.25rem 1.5rem; font-size: 0.88rem; line-height: 1.8; color: #1e293b; margin-top: 1rem; }}
    .htable {{ width: 100%; border-collapse: collapse; font-size: 0.85rem; background: #fff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.06); }}
    .htable th {{ background: #f1f5f9; font-weight: 600; padding: 0.55rem 0.85rem; text-align: left; border-bottom: 2px solid #e2e8f0; color: #475569; font-size: 0.78rem; text-transform: uppercase; letter-spacing: 0.04em; }}
    .htable td {{ padding: 0.4rem 0.85rem; border-bottom: 1px solid #f1f5f9; }}
    .htable tr:hover td {{ background: #f8fafc; }}
    .htable tr:last-child td {{ border-bottom: none; }}
    .as-of {{ font-size: 0.78rem; color: #94a3b8; margin-bottom: 0.5rem; }}
    footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e2e8f0; font-size: 0.78rem; color: #94a3b8; }}
    footer a {{ color: #94a3b8; }}
  </style>
</head>
<body>
<div class="container">

  <div class="fund-header">
    <div class="ticker">NYSE Arca · GVIP</div>
    <h1>{FUND_NAME}</h1>
    <p class="objective">{FUND_OBJECTIVE}</p>
    <div class="perf-grid">
      <div class="perf-card">
        <div class="label">Price</div>
        <div class="value">${perf['price']:.2f}</div>
      </div>
      <div class="perf-card">
        <div class="label">AUM</div>
        <div class="value">${aum_m:.0f}M</div>
      </div>
      <div class="perf-card">
        <div class="label">1 Month</div>
        <div class="value" style="color:{c1m}">{ret_1m}</div>
      </div>
      <div class="perf-card">
        <div class="label">3 Month</div>
        <div class="value" style="color:{c3m}">{ret_3m}</div>
      </div>
      <div class="perf-card">
        <div class="label">YTD</div>
        <div class="value" style="color:{cytd}">{ret_ytd}</div>
      </div>
      <div class="perf-card">
        <div class="label">1 Year</div>
        <div class="value" style="color:{c1y}">{ret_1y}</div>
      </div>
    </div>
    {week52_bar}
    <div class="meta-bar">
      <span>As of <b>{perf['as_of']}</b></span>
      <span>Avg Volume <b>{perf.get('avg_volume', 0):,}</b></span>
      <span>Holdings as of <b>{holdings_as_of}</b></span>
    </div>
  </div>

  <h2>Analyst Commentary</h2>
  {summary_html}

  <h2>Price Performance vs SPY — 1 Year (Indexed to 100)</h2>
  {p_chart}

  <h2>Conviction vs Momentum — Quadrant View</h2>
  {q_chart}
  {f'<div class="quadrant-commentary-box">{quadrant_commentary.replace(chr(10), "<br>")}</div>' if quadrant_commentary else ''}

  <h2>Relative Positioning — GVIP vs MTUM</h2>
  {rp_chart}

  <h2>Sector Allocation</h2>
  {s_chart}

  <h2>Position Changes</h2>
  {change_html}

  <h2>All Holdings — {holdings_as_of}</h2>
  <p class="as-of">Source: stockanalysis.com · {len(holdings)} positions</p>
  {holdings_html}

  <footer>
    Source: <a href="https://am.gs.com/en-us/institutions/funds/detail/PV102634/381430545/goldman-sachs-hedge-industry-vip-etf" target="_blank">Goldman Sachs Asset Management</a> ·
    Data via <a href="https://stockanalysis.com/etf/gvip/holdings/" target="_blank">Stock Analysis</a> &amp; yfinance ·
    Generated by Claude Code ·
    <a href="https://github.com/DataVizHonduran/boquin.github.io" target="_blank">Source</a>
  </footer>
</div>
</body>
</html>"""

# ── Publishing ─────────────────────────────────────────────────────────────────

LANDING_CARD = """<article class="dashboard-card">
    <div class="card-header">
        <h3>📊 GVIP — Hedge Industry VIP ETF</h3>
        <p>Daily holdings tracker for the Goldman Sachs Hedge Fund VIP Index, with sector breakdown, position change log, and AI-generated analyst commentary.</p>
    </div>
    <div class="card-actions">
        <a href="reports/gvip/index.html" class="btn btn-primary">Launch Dashboard</a>
        <a href="https://github.com/DataVizHonduran/boquin.github.io/blob/main/scripts/generate_gvip.py" class="btn btn-secondary">Source Code</a>
    </div>
</article>"""


def add_landing_card():
    if not LANDING_PAGE.exists():
        return
    content = LANDING_PAGE.read_text()
    if "reports/gvip" in content:
        return
    marker = '            </div>\n        </section>\n    </main>'
    if marker not in content:
        print("  ⚠ Could not find landing page insertion point; skipping card addition")
        return
    card_indented = '\n'.join('                ' + line if line.strip() else line for line in LANDING_CARD.strip().split('\n'))
    updated = content.replace(marker, f'{card_indented}\n            </div>\n        </section>\n    </main>', 1)
    LANDING_PAGE.write_text(updated)
    print("  ✓ Added landing card to index.html")


def publish(today: str, added_landing_card: bool):
    repo = Path.home() / "boquin.github.io"
    files = [str(REPORT_DIR / "index.html")]
    if added_landing_card:
        files.append(str(LANDING_PAGE))

    cmds = [
        ["git", "-C", str(repo), "pull"],
        ["git", "-C", str(repo), "add"] + files,
        ["git", "-C", str(repo), "commit", "-m", f"Update GVIP Holdings Monitor — {today}"],
        ["git", "-C", str(repo), "pull", "--rebase"],
        ["git", "-C", str(repo), "push"],
    ]
    for cmd in cmds:
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"  ⚠ git error: {result.stderr.strip()}", file=sys.stderr)
        else:
            print(f"  ✓ {' '.join(cmd[3:])}")

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--cache-only", action="store_true")
    parser.add_argument("--no-publish", action="store_true")
    parser.add_argument("--print-context", action="store_true")
    parser.add_argument("--summary-file", type=str)
    parser.add_argument("--quadrant-file", type=str)
    args = parser.parse_args()

    today = date.today().strftime("%Y-%m-%d")
    today_path = snapshot_path(today)

    # Step 1: Load or fetch data
    if args.cache_only or today_path.exists():
        if today_path.exists():
            print(f"Loading today's snapshot: {today_path.name}", file=sys.stderr)
            with open(today_path) as f:
                today_data = json.load(f)
        else:
            files = sorted(CACHE_DIR.glob("*.json"))
            if not files:
                print("ERROR: No cached snapshots found.", file=sys.stderr)
                sys.exit(1)
            print(f"Cache-only mode: loading {files[-1].name}", file=sys.stderr)
            with open(files[-1]) as f:
                today_data = json.load(f)
            today = today_data["date"]
    else:
        print("Fetching GVIP data...")
        holdings = fetch_holdings()
        print("Fetching performance data from yfinance...")
        performance = fetch_performance()
        print("Fetching sector weights...")
        sectors = fetch_sector_weights()

        today_data = {
            "date": today,
            "holdings_as_of": today,
            "holdings": holdings,
            "performance": performance,
            "sectors": sectors,
        }
        save_snapshot(today_data, today)

    # Step 2: Prior snapshot for diff (~2 weeks ago)
    prior_snapshot = snapshot_two_weeks_ago(today)
    prior_date = prior_snapshot["date"] if prior_snapshot else None

    diff = {}
    if prior_snapshot:
        diff = compute_diff(today_data["holdings"], prior_snapshot.get("holdings", []))

    # --print-context
    if args.print_context:
        print_context_for_claude(today_data, diff, prior_date)
        return

    # Step 3: Summary
    summary = ""
    fresh_summary = False
    if args.summary_file:
        summary = Path(args.summary_file).read_text().strip()
        print(f"  ✓ Summary loaded from {args.summary_file} ({len(summary.split())} words)")
        fresh_summary = True
    else:
        hf_token = os.environ.get("HF_TOKEN")
        if hf_token and should_refresh_summary():
            meta = load_summary_meta()
            last_date = meta.get("generated_at", "never")
            print(f"  ↻ Commentary stale (last: {last_date}), refreshing via Gemma 4...")
            context_text = build_context(today_data, diff)
            try:
                summary = generate_summary_gemma(context_text, hf_token)
                save_summary_meta(datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"), len(summary.split()))
                print(f"  ✓ Gemma summary generated ({len(summary.split())} words)")
                fresh_summary = True
            except Exception as e:
                print(f"  WARNING: Gemma generation failed ({e}), falling back to existing",
                      file=sys.stderr)
                summary = extract_existing_summary()
        else:
            summary = extract_existing_summary()
            if summary:
                print(f"  ✓ Preserved existing summary ({len(summary.split())} words)")

    # Step 4: Price history + momentum + render
    print("Fetching 1-year price history (GVIP + SPY)...")
    price_history = fetch_price_history()
    print("Fetching 3-month momentum for holdings...")
    momentum = fetch_holding_momentum(today_data["holdings"])
    print(f"  ✓ Momentum data for {len(momentum)} tickers")
    print("Fetching fundamentals (fwd P/E + short interest) for holdings...")
    holding_tickers = [h["ticker"] for h in today_data["holdings"]]
    fundamentals = fetch_holding_fundamentals(holding_tickers)
    valid_pe = sum(1 for v in fundamentals["pe"].values() if v is not None)
    valid_si = sum(1 for v in fundamentals["short"].values() if v is not None)
    print(f"  ✓ Fwd P/E: {valid_pe}/{len(holding_tickers)}  Short interest: {valid_si}/{len(holding_tickers)}")
    print("Fetching MTUM holdings...")
    try:
        mtum_holdings = fetch_mtum_holdings()
    except Exception as e:
        print(f"  ⚠ MTUM fetch failed ({e}), skipping relative positioning chart", file=sys.stderr)
        mtum_holdings = {}
    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC") if fresh_summary else None

    # Step 4b: Quadrant commentary
    quadrant_commentary = ""
    if args.quadrant_file:
        quadrant_commentary = Path(args.quadrant_file).read_text().strip()
        save_quadrant_meta(datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"), len(quadrant_commentary.split()))
        print(f"  ✓ Quadrant commentary loaded from {args.quadrant_file} ({len(quadrant_commentary.split())} words)")
    hf_token = os.environ.get("HF_TOKEN")
    if not quadrant_commentary and hf_token and should_refresh_quadrant_commentary():
        print("  ↻ Quadrant commentary stale, generating via Gemma 4...")
        try:
            q_context = build_quadrant_context(today_data["holdings"], momentum, fundamentals)
            quadrant_commentary = generate_quadrant_commentary_gemma(q_context, hf_token)
            save_quadrant_meta(datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"), len(quadrant_commentary.split()))
            print(f"  ✓ Quadrant commentary generated ({len(quadrant_commentary.split())} words)")
        except Exception as e:
            print(f"  WARNING: Quadrant commentary failed ({e}), falling back to existing", file=sys.stderr)
            quadrant_commentary = extract_existing_quadrant_commentary()
    elif not quadrant_commentary:
        quadrant_commentary = extract_existing_quadrant_commentary()
        if quadrant_commentary:
            print(f"  ✓ Preserved existing quadrant commentary ({len(quadrant_commentary.split())} words)")

    snapshots = load_snapshots()

    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    html = render_html(today_data, diff, summary, snapshots, prior_date, price_history, momentum, fundamentals, quadrant_commentary, generated_at, mtum_holdings)
    out_path = REPORT_DIR / "index.html"
    out_path.write_text(html)
    print(f"  ✓ Report written: {out_path}")

    # Step 5: Publish
    if not args.no_publish:
        added_card = False
        if LANDING_PAGE.exists():
            content = LANDING_PAGE.read_text()
            if "reports/gvip" not in content:
                add_landing_card()
                added_card = True
        print("Publishing to boquin.github.io...")
        publish(today, added_card)
        print(f"  ✓ Published: https://boquin.xyz/reports/gvip/")
    else:
        print("Skipping publish (--no-publish).")


if __name__ == "__main__":
    main()
