#!/usr/bin/env python3
"""
Unlimited ETFs Holdings Monitor
Fetches daily holdings CSVs for HFND, HFGM, HFMF, HFEQ,
saves a rolling 20-day archive, and publishes an HTML report.

Commentary is generated by Gemma 4 via HuggingFace (refreshed daily).

Flags:
  --cache-only            Skip CSV fetch; use latest cached snapshot
  --no-publish            Generate HTML but skip git push
  --print-context         Print JSON context for Claude to summarize, then exit
  --summary-file PATH     Read summary from file instead of generating

GitHub Actions secrets required:
  HF_TOKEN                HuggingFace API token (for auto commentary refresh)
"""

import os
import sys
import csv
import json
import glob
import time
import argparse
import subprocess
import io
from datetime import datetime, date, timedelta
from pathlib import Path

import requests
from bs4 import BeautifulSoup
from huggingface_hub import InferenceClient

# ── Config ────────────────────────────────────────────────────────────────────

ETF_TICKERS = ["HFND", "HFGM", "HFMF", "HFEQ"]
ETF_NAMES = {
    "HFND": "Hedge Fund ETF",
    "HFGM": "Global Macro ETF",
    "HFMF": "Multi-Factor ETF",
    "HFEQ": "Equity ETF",
}
CSV_URL = "https://unlimitedetfs.com/wp-content/uploads/data/TidalFG_Holdings_{ticker}.csv"

# ── Asset Class Classification ────────────────────────────────────────────────

TICKER_ASSET_CLASS = {
    # Currencies (CME FX futures — Bloomberg "Curncy" suffix)
    "ECM6 Curncy": "currencies", "ECU6 Curncy": "currencies", "ECZ6 Curncy": "currencies",
    "ADM6 Curncy": "currencies", "ADU6 Curncy": "currencies",
    "SFM6 Curncy": "currencies", "SFU6 Curncy": "currencies",
    "CDM6 Curncy": "currencies", "CDU6 Curncy": "currencies",
    "BPM6 Curncy": "currencies", "BPU6 Curncy": "currencies",
    "JYM6 Curncy": "currencies", "JYU6 Curncy": "currencies",
    "DXM6 Curncy": "currencies", "DXU6 Curncy": "currencies",
    # Currencies (bare tickers as fallback)
    "ECM6": "currencies", "ADM6": "currencies", "SFM6": "currencies",
    "CDM6": "currencies", "BPM6": "currencies", "JYM6": "currencies", "DXM6": "currencies",
    # Commodities (Bloomberg "Comdty" suffix)
    "GCM6 Comdty": "commodities", "GCZ6 Comdty": "commodities", "GCQ6 Comdty": "commodities",
    "HGK6 Comdty": "commodities", "HGN6 Comdty": "commodities",
    "SBK6 Comdty": "commodities", "SBN6 Comdty": "commodities",
    "CCK6 Comdty": "commodities", "CCN6 Comdty": "commodities",
    "CLM6 Comdty": "commodities", "CLN6 Comdty": "commodities",
    "C K6 Comdty": "commodities",   # Corn
    "S K6 Comdty": "commodities",   # Soybean
    "KCK6 Comdty": "commodities",   # Coffee
    "LCJ6 Comdty": "commodities",   # Live Cattle
    # Commodities (ETFs / bare)
    "DBB": "commodities", "GLD": "commodities", "IAU": "commodities",
    "SLV": "commodities", "USO": "commodities",
    # Equities (Bloomberg "Index" suffix — futures)
    "ESM6 Index": "equities", "ESU6 Index": "equities",
    "NQM6 Index": "equities", "NQU6 Index": "equities",
    "MESM6 Index": "equities", "MFSM6 Index": "equities",
    "NXM6 Index": "equities", "VGM6 Index": "equities",
    "IXAM6 Index": "equities", "DNM6 Index": "equities",
    "XARM6 Index": "equities", "UXJ6 Index": "equities",
    # Equities (ETFs / bare)
    "VTV": "equities", "VUG": "equities", "VO": "equities", "VTWO": "equities",
    "VGK": "equities", "VFMO": "equities",
    "XLF": "equities", "XLE": "equities", "XLI": "equities", "XLB": "equities",
    "XLY": "equities", "XLP": "equities", "XLU": "equities",
    "XBI": "equities", "XHB": "equities", "XRT": "equities",
    "EWW": "equities", "EWY": "equities", "EWZ": "equities", "EZA": "equities",
    "MCHI": "equities",
    "SPY": "equities", "QQQ": "equities", "IWM": "equities",
    "EEM": "equities", "EFA": "equities",
    # Fixed Income (Bloomberg "Comdty" suffix — Treasury futures)
    "FVM6 Comdty": "fixed_income", "FVU6 Comdty": "fixed_income",
    "USM6 Comdty": "fixed_income", "USU6 Comdty": "fixed_income",
    "TYM6 Comdty": "fixed_income", "TYU6 Comdty": "fixed_income",
    "ZNM6 Comdty": "fixed_income", "ZNU6 Comdty": "fixed_income",
    # Fixed Income (Bloomberg "Index" suffix — credit futures)
    "IBYM6 Index": "fixed_income",
    # Fixed Income (ETFs / bare)
    "VWOB": "fixed_income", "AGZ": "fixed_income",
    "AGG": "fixed_income", "LQD": "fixed_income",
    "HYG": "fixed_income", "JNK": "fixed_income",
    "BKLN": "fixed_income", "EMHY": "fixed_income", "ICVT": "fixed_income",
}


TICKER_SHORT_NAME = {
    # Currencies
    "ECM6 Curncy": "Euro FX",     "ECU6 Curncy": "Euro FX",
    "ADM6 Curncy": "AUD/USD",     "ADU6 Curncy": "AUD/USD",
    "SFM6 Curncy": "Swiss Franc", "SFU6 Curncy": "Swiss Franc",
    "CDM6 Curncy": "CAD",         "CDU6 Curncy": "CAD",
    "BPM6 Curncy": "GBP",         "BPU6 Curncy": "GBP",
    "JYM6 Curncy": "Yen",         "JYU6 Curncy": "Yen",
    "DXM6 Curncy": "Dollar Index","DXU6 Curncy": "Dollar Index",
    # Commodities
    "GCM6 Comdty": "Gold",        "GCZ6 Comdty": "Gold",
    "HGK6 Comdty": "Copper",      "HGN6 Comdty": "Copper",
    "SBK6 Comdty": "Sugar",       "SBN6 Comdty": "Sugar",
    "CCK6 Comdty": "Cocoa",       "CCN6 Comdty": "Cocoa",
    "CLM6 Comdty": "WTI Crude",   "CLN6 Comdty": "WTI Crude",
    "C K6 Comdty": "Corn",
    "S K6 Comdty": "Soybean",
    "KCK6 Comdty": "Coffee",
    "LCJ6 Comdty": "Live Cattle",
    "DBB": "Base Metals ETF",
    # Equities — futures
    "ESM6 Index":  "S&P E-mini",  "ESU6 Index":  "S&P E-mini",
    "NQM6 Index":  "Nasdaq E-mini","NQU6 Index": "Nasdaq E-mini",
    "MESM6 Index": "MSCI EM",     "MFSM6 Index": "MSCI EAFE",
    "NXM6 Index":  "Nikkei 225",  "VGM6 Index":  "Euro Stoxx 50",
    "IXAM6 Index": "XAF Financial","DNM6 Index":  "BCOM Index",
    "XARM6 Index": "S&P RE E-mini","UXJ6 Index":  "VIX",
    # Equities — ETFs
    "VTV": "Vanguard Value",  "VUG": "Vanguard Growth",
    "VO":  "Mid-Cap ETF",     "VTWO": "Russell 2000",
    "VGK": "FTSE Europe",     "VFMO": "Momentum ETF",
    "XLF": "Financials",      "XLE": "Energy",
    "XLI": "Industrials",     "XLB": "Materials",
    "XLY": "Cons. Disc.",     "XLP": "Cons. Staples",
    "XLU": "Utilities",       "XBI": "Biotech",
    "XHB": "Homebuilders",    "XRT": "Retail",
    "EWW": "MSCI Mexico",     "EWY": "MSCI S. Korea",
    "EWZ": "MSCI Brazil",     "EZA": "MSCI S. Africa",
    "MCHI": "MSCI China",
    # Fixed Income
    "FVM6 Comdty": "5Y Treasury", "FVU6 Comdty": "5Y Treasury",
    "TYM6 Comdty": "10Y Treasury","TYU6 Comdty": "10Y Treasury",
    "USM6 Comdty": "30Y Bond",    "USU6 Comdty": "30Y Bond",
    "IBYM6 Index": "HY Credit",
    "VWOB": "EM Gov Bonds",   "AGZ": "Agency Bonds",
    "LQD": "IG Corp Bonds",   "BKLN": "Senior Loans",
    "EMHY": "EM High Yield",  "ICVT": "Convert. Bonds",
}


def classify_ticker(ticker: str, name: str):
    if ticker in TICKER_ASSET_CLASS:
        return TICKER_ASSET_CLASS[ticker]
    n = name.lower()
    if any(k in n for k in ("euro fx", "yen", "pound", "franc", "dollar index", "aud/", "cad/", "currency")):
        return "currencies"
    if any(k in n for k in ("gold", "silver", "copper", "crude", "oil", "sugar", "cocoa", "wheat", "corn", "commodity", "metal")):
        return "commodities"
    if any(k in n for k in ("treasury", "note", "bond", "yield", "credit", "high yield", "fixed income", "sovereign", "government bond")):
        return "fixed_income"
    if any(k in n for k in ("s&p", "nasdaq", "russell", "stoxx", "nikkei", "equity", "stock", "msci", "financial", "sector")):
        return "equities"
    return None


CACHE_DIR = Path(os.environ.get("ETF_CACHE_DIR", str(Path.home() / ".claude" / "cache" / "unlimited-etfs")))
REPORT_DIR = Path(os.environ.get("ETF_REPORT_DIR", str(Path.home() / "boquin.github.io" / "reports" / "unlimited-etfs")))
LANDING_PAGE = Path(os.environ.get("ETF_LANDING_PAGE", str(Path.home() / "boquin.github.io" / "index.html")))

MAX_SNAPSHOTS = 20
SUMMARY_REFRESH_DAYS = 1
SUMMARY_META_FILE = REPORT_DIR / "summary_meta.json"

MODEL_ID = "google/gemma-4-26B-A4B-it"

SYSTEM_PROMPT = """\
You are a macro analyst at a top hedge fund. The user will provide you with a \
structured snapshot of the four Unlimited ETFs (HFND, HFGM, HFMF, HFEQ): \
current AUM, net/gross exposure, top positions, and recent position changes.

Write a concise analyst commentary (STRICT maximum 500 words) covering: \
overall risk-on/risk-off stance across the suite, sector tilts, geographic \
exposure (EM vs DM), notable position changes, and what the collective \
positioning implies for macro expectations.

Open with a 'Key macro themes' paragraph (2-3 sentences) that summarises the \
dominant cross-ETF bets — what is the suite collectively expressing? Then \
continue with fund-by-fund detail.

Style: flowing prose, no bullet points, no headers, precise and insightful. \
Anchor every judgment in the numbers provided.

Asset naming: always use plain English names instead of futures ticker codes. \
For example, write "yen" not "JYU6", "euro" not "ECM6", "pound" not "BPM6", \
"Australian dollar" not "ADM6", "Swiss franc" not "SFM6", "Canadian dollar" \
not "CDM6", "dollar index" not "DXM6". Apply the same principle to all \
instruments — describe the underlying asset, not the contract code.

Directionality: reason about currency positions correctly. A long futures \
position on a foreign currency is a bet on that currency strengthening against \
the dollar; a short is a bet on it weakening. Never conflate a short foreign \
currency position with a dollar-bearish view, and never conflate a long foreign \
currency position with a dollar-bullish view. State the directional implication \
explicitly and accurately.\
"""

# ── Performance ──────────────────────────────────────────────────────────────

ETF_PAGES = {
    "HFND": "https://unlimitedetfs.com/hfnd/",
    "HFGM": "https://unlimitedetfs.com/hfgm/",
    "HFMF": "https://unlimitedetfs.com/hfmf/",
    "HFEQ": "https://unlimitedetfs.com/hfeq/",
}

def fetch_performance() -> dict:
    """Scrape 1MO and YTD returns (MKT price) from each ETF page on unlimitedetfs.com."""
    perf = {}
    headers = {"User-Agent": "unlimited-etfs-monitor research@claude.local"}
    for ticker in ETF_TICKERS:
        try:
            resp = requests.get(ETF_PAGES[ticker], timeout=15, headers=headers)
            resp.raise_for_status()
            soup = BeautifulSoup(resp.text, "html.parser")

            # Find the wpDataTable that has performance columns (1MO, YTD)
            table = None
            for t in soup.find_all("table", class_="wpDataTable"):
                thead = t.find("thead")
                if thead and "1MO" in thead.get_text().upper():
                    table = t
                    break
            if not table:
                raise ValueError("performance wpDataTable not found")

            # Parse column headers
            headers_row = table.find("thead").find_all("th")
            cols = [th.get_text(strip=True).upper() for th in headers_row]

            # Find the MKT row (first tbody row)
            rows = table.find("tbody").find_all("tr")
            mkt_row = next(
                (r for r in rows if "MKT" in r.get_text().upper()),
                rows[0]
            )
            cells = [td.get_text(strip=True) for td in mkt_row.find_all("td")]

            def get_val(col_name):
                if col_name in cols:
                    idx = cols.index(col_name)
                    if idx < len(cells):
                        return cells[idx].replace("%", "").strip()
                return None

            def parse_pct(s):
                try:
                    return float(s) if s else None
                except (ValueError, TypeError):
                    return None

            # Find the "as of" date — look for text like "as of MM/DD/YYYY"
            as_of = None
            for tag in soup.find_all(string=lambda t: t and "as of" in t.lower()):
                import re
                m = re.search(r"\d{2}/\d{2}/\d{4}", tag)
                if m:
                    as_of = m.group()
                    break

            perf[ticker] = {
                "ret_1m": parse_pct(get_val("1MO")),
                "ret_ytd": parse_pct(get_val("YTD")),
                "ret_3m": parse_pct(get_val("3MO")),
                "as_of": as_of,
            }
        except Exception as e:
            print(f"  ⚠ Performance fetch failed for {ticker}: {e}", file=sys.stderr)
            perf[ticker] = {"ret_1m": None, "ret_ytd": None, "ret_3m": None, "as_of": None}
    return perf


def fmt_ret(val: float | None) -> tuple[str, str]:
    """Return (formatted string, color) for a return value."""
    if val is None:
        return "n/a", "#6b7280"
    sign = "+" if val >= 0 else ""
    color = "#16a34a" if val >= 0 else "#dc2626"
    return f"{sign}{val:.1f}%", color


# ── Fetch & Parse ─────────────────────────────────────────────────────────────

def fetch_csv(ticker: str) -> list[dict] | None:
    url = CSV_URL.format(ticker=ticker)
    try:
        resp = requests.get(url, timeout=15, headers={"User-Agent": "unlimited-etfs-monitor research@claude.local"})
        resp.raise_for_status()
        reader = csv.DictReader(io.StringIO(resp.text))
        rows = []
        for row in reader:
            rows.append(parse_row(row))
        print(f"  ✓ {ticker}: {len(rows)} positions fetched")
        return rows
    except Exception as e:
        print(f"  ✗ {ticker}: fetch failed ({e})", file=sys.stderr)
        return None


def parse_row(row: dict) -> dict:
    def safe_float(val, default=0.0):
        try:
            return float(str(val).replace(",", "").replace("%", "").strip())
        except (ValueError, TypeError):
            return default

    weight_str = row.get("Weightings", "0").replace("%", "").strip()
    return {
        "StockTicker": row.get("StockTicker", "").strip(),
        "SecurityName": row.get("SecurityName", "").strip(),
        "Shares": safe_float(row.get("Shares", 0)),
        "Price": safe_float(row.get("Price", 0)),
        "MarketValue": safe_float(row.get("MarketValue", 0)),
        "Weightings": safe_float(weight_str),
        "NetAssets": safe_float(row.get("NetAssets", 0)),
    }

# ── Cache ─────────────────────────────────────────────────────────────────────

def snapshot_path(d: str) -> Path:
    return CACHE_DIR / f"{d}.json"


def save_snapshot(data: dict, today: str):
    path = snapshot_path(today)
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
    print(f"  Saved snapshot: {path.name}")
    prune_snapshots()


def prune_snapshots():
    files = sorted(CACHE_DIR.glob("*.json"))
    while len(files) > MAX_SNAPSHOTS:
        files[0].unlink()
        print(f"  Pruned old snapshot: {files[0].name}")
        files = files[1:]


def load_snapshots() -> list[dict]:
    """Load all cached snapshots sorted oldest→newest."""
    files = sorted(CACHE_DIR.glob("*.json"))
    snapshots = []
    for f in files:
        with open(f) as fh:
            snapshots.append(json.load(fh))
    return snapshots


def latest_snapshot_before(today: str) -> dict | None:
    files = sorted(CACHE_DIR.glob("*.json"))
    candidates = [f for f in files if f.stem < today]
    if not candidates:
        return None
    with open(candidates[-1]) as fh:
        return json.load(fh)

# ── Metrics ───────────────────────────────────────────────────────────────────

CASH_KEYWORDS = {"cash", "money market", "government obligations", "treasury", "fgxxx", "cash&other"}

def is_cash(row: dict) -> bool:
    name_lower = row["SecurityName"].lower()
    ticker_lower = row["StockTicker"].lower()
    return any(kw in name_lower or kw in ticker_lower for kw in CASH_KEYWORDS)


def compute_etf_metrics(holdings: list[dict]) -> dict:
    net_assets = holdings[0]["NetAssets"] if holdings else 0
    longs = [h for h in holdings if h["Weightings"] > 0 and not is_cash(h)]
    shorts = [h for h in holdings if h["Weightings"] < 0]
    cash_rows = [h for h in holdings if is_cash(h)]

    gross_long = sum(h["Weightings"] for h in longs)
    gross_short = abs(sum(h["Weightings"] for h in shorts))
    net_exposure = gross_long - gross_short
    cash_pct = sum(h["Weightings"] for h in cash_rows)

    top5 = sorted(holdings, key=lambda h: abs(h["Weightings"]), reverse=True)[:5]

    return {
        "net_assets": net_assets,
        "gross_long": gross_long,
        "gross_short": gross_short,
        "net_exposure": net_exposure,
        "cash_pct": cash_pct,
        "top5": top5,
        "n_longs": len(longs),
        "n_shorts": len(shorts),
    }


def compute_diff(today_holdings: list[dict], prior_holdings: list[dict]) -> dict:
    today_map = {h["StockTicker"]: h for h in today_holdings}
    prior_map = {h["StockTicker"]: h for h in prior_holdings}

    new_positions = [today_map[t] for t in today_map if t not in prior_map and t not in ("Cash&Other",)]
    removed = [prior_map[t] for t in prior_map if t not in today_map and t not in ("Cash&Other",)]
    changed = []
    for ticker in today_map:
        if ticker in prior_map:
            delta = today_map[ticker]["Weightings"] - prior_map[ticker]["Weightings"]
            if abs(delta) >= 1.5:
                changed.append({
                    "ticker": ticker,
                    "name": today_map[ticker]["SecurityName"],
                    "today": today_map[ticker]["Weightings"],
                    "prior": prior_map[ticker]["Weightings"],
                    "delta": delta,
                })

    return {"new": new_positions, "removed": removed, "changed": changed}

# ── Claude Summary ────────────────────────────────────────────────────────────

def build_context_prompt(today_data: dict, metrics: dict, diffs: dict) -> str:
    lines = [f"Date: {today_data['date']}\n"]
    for ticker in ETF_TICKERS:
        m = metrics[ticker]
        lines.append(f"## {ticker} — {ETF_NAMES[ticker]}")
        lines.append(f"AUM: ${m['net_assets']:,.0f} | Net Exposure: {m['net_exposure']:.1f}% | Gross Long: {m['gross_long']:.1f}% | Gross Short: {m['gross_short']:.1f}% | Cash: {m['cash_pct']:.1f}%")
        lines.append("Top 5 positions (by |weight|):")
        for h in m["top5"]:
            sign = "+" if h["Weightings"] >= 0 else ""
            lines.append(f"  {h['StockTicker']:20s} {sign}{h['Weightings']:.2f}%  {h['SecurityName']}")

        d = diffs.get(ticker, {})
        if d.get("new"):
            lines.append("New positions: " + ", ".join(f"{h['StockTicker']} ({h['Weightings']:+.1f}%)" for h in d["new"]))
        if d.get("removed"):
            lines.append("Removed: " + ", ".join(h["StockTicker"] for h in d["removed"]))
        if d.get("changed"):
            lines.append("Weight changes: " + ", ".join(f"{c['ticker']} {c['prior']:.1f}%→{c['today']:.1f}% ({c['delta']:+.1f}%)" for c in d["changed"]))
        lines.append("")

    return "\n".join(lines)


def snapshot_before_days(today: str, days: int) -> dict | None:
    """Return the snapshot closest to `days` calendar days before today, or oldest available."""
    cutoff = (datetime.strptime(today, "%Y-%m-%d") - timedelta(days=days)).strftime("%Y-%m-%d")
    files = sorted(CACHE_DIR.glob("*.json"))
    candidates = [f for f in files if f.stem < today]
    if not candidates:
        return None
    # Pick the file on or just before the cutoff; fall back to oldest if none reach that far
    before_cutoff = [f for f in candidates if f.stem <= cutoff]
    target = before_cutoff[-1] if before_cutoff else candidates[0]
    with open(target) as fh:
        return json.load(fh)


def build_gemma_context(today_data: dict, metrics: dict, window_days: int = 5) -> str:
    """Build context for Gemma using position changes over the last `window_days` days."""
    baseline = snapshot_before_days(today_data["date"], window_days)
    baseline_date = baseline["date"] if baseline else None

    rolling_diffs = {}
    if baseline:
        for ticker in ETF_TICKERS:
            rolling_diffs[ticker] = compute_diff(
                today_data["etfs"][ticker],
                baseline["etfs"].get(ticker, []),
            )

    lines = [f"Date: {today_data['date']}"]
    if baseline_date:
        lines.append(f"Position changes shown vs {baseline_date} ({window_days}-day window)\n")
    else:
        lines.append("")

    for ticker in ETF_TICKERS:
        m = metrics[ticker]
        lines.append(f"## {ticker} — {ETF_NAMES[ticker]}")
        lines.append(
            f"AUM: ${m['net_assets']:,.0f} | Net Exposure: {m['net_exposure']:.1f}% | "
            f"Gross Long: {m['gross_long']:.1f}% | Gross Short: {m['gross_short']:.1f}% | "
            f"Cash: {m['cash_pct']:.1f}%"
        )
        lines.append("Top 5 positions (by |weight|):")
        for h in m["top5"]:
            sign = "+" if h["Weightings"] >= 0 else ""
            lines.append(f"  {h['StockTicker']:20s} {sign}{h['Weightings']:.2f}%  {h['SecurityName']}")

        d = rolling_diffs.get(ticker, {})
        if d.get("new"):
            lines.append("Added over window: " + ", ".join(
                f"{h['StockTicker']} ({h['Weightings']:+.1f}%)" for h in d["new"]))
        if d.get("removed"):
            lines.append("Removed over window: " + ", ".join(h["StockTicker"] for h in d["removed"]))
        if d.get("changed"):
            lines.append("Net weight shifts: " + ", ".join(
                f"{c['ticker']} {c['prior']:.1f}%→{c['today']:.1f}% ({c['delta']:+.1f}%)"
                for c in d["changed"]))
        lines.append("")

    return "\n".join(lines)


def print_context_for_claude(today_data: dict, metrics: dict, diffs: dict, prior_date: str | None):
    """Print a JSON blob to stdout for Claude to read and summarize."""
    context_text = build_context_prompt(today_data, metrics, diffs)
    out = {
        "date": today_data["date"],
        "prior_date": prior_date,
        "context_text": context_text,
        "instruction": (
            "You are a macro analyst. Write a concise analyst commentary (STRICT maximum 500 words) "
            "on the current positioning of the four Unlimited ETFs (HFND, HFGM, HFMF, HFEQ). "
            "Cover: overall risk-on/risk-off stance, sector tilts, geographic exposure (EM vs DM), "
            "notable position changes, and what the positioning implies for macro expectations. "
            "Start with a 'Key macro themes' opening paragraph (2-3 sentences) that summarizes the dominant cross-ETF bets — what is the suite collectively expressing? "
            "Then continue with fund-by-fund detail. "
            "Write in flowing prose, no bullet points, no headers. Be precise and insightful."
        ),
    }
    print(json.dumps(out, indent=2))

# ── HTML Rendering ─────────────────────────────────────────────────────────────

def aum_chart_js(snapshots: list[dict]) -> str:
    colors = {"HFND": "#2563eb", "HFGM": "#16a34a", "HFMF": "#d97706", "HFEQ": "#dc2626"}
    dates = [s["date"] for s in snapshots]
    datasets = []
    for ticker in ETF_TICKERS:
        aum_series = []
        for s in snapshots:
            holdings = s["etfs"].get(ticker, [])
            aum = holdings[0]["NetAssets"] / 1e6 if holdings else None
            aum_series.append(aum)
        ds = {
            "label": ticker,
            "data": aum_series,
            "borderColor": colors[ticker],
            "backgroundColor": colors[ticker] + "22",
            "tension": 0.3,
            "fill": False,
            "spanGaps": True,
        }
        datasets.append(json.dumps(ds))
    labels_json = json.dumps(dates)
    datasets_json = "[" + ", ".join(datasets) + "]"

    return f"""
<div style="max-width:800px;margin:0 auto 2rem;">
  <canvas id="aumChart" height="120"></canvas>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
<script>
new Chart(document.getElementById('aumChart'), {{
  type: 'line',
  data: {{ labels: {labels_json}, datasets: {datasets_json} }},
  options: {{
    responsive: true,
    plugins: {{
      title: {{ display: true, text: 'AUM History (USD Millions)', font: {{size: 14}} }},
      legend: {{ position: 'top' }}
    }},
    scales: {{
      y: {{ title: {{ display: true, text: 'USD Millions' }} }}
    }}
  }}
}});
</script>"""


def positioning_bar_chart_js(today_data: dict) -> str:
    CLASS_COLORS = {
        "currencies":  "#8b5cf6",
        "commodities": "#d97706",
        "equities":    "#2563eb",
        "fixed_income": "#16a34a",
    }
    CLASS_LABELS = {
        "currencies":  "Currencies",
        "commodities": "Commodities",
        "equities":    "Equities",
        "fixed_income": "Fixed Income",
    }

    candidates = []
    for etf, holdings in today_data["etfs"].items():
        for h in holdings:
            if is_cash(h) or h["Weightings"] == 0:
                continue
            cls = classify_ticker(h["StockTicker"], h["SecurityName"])
            if cls is None:
                continue
            candidates.append({
                "label": f'{TICKER_SHORT_NAME.get(h["StockTicker"], h["StockTicker"].split()[0])} ({etf})',
                "weight": h["Weightings"],
                "cls": cls,
            })

    bars = []
    for cls in CLASS_COLORS:
        cls_items = [c for c in candidates if c["cls"] == cls]
        # Group by asset name (strip " (ETF)" suffix) so the same asset in multiple
        # ETFs can't dominate both top-2 slots. Keep the highest-weight entry per name.
        name_to_best: dict = {}
        for item in cls_items:
            name = item["label"].rsplit(" (", 1)[0]
            if name not in name_to_best or item["weight"] > name_to_best[name]["weight"]:
                name_to_best[name] = item
        unique_assets = list(name_to_best.values())
        longs  = sorted(unique_assets, key=lambda x: x["weight"], reverse=True)[:2]
        shorts = sorted(unique_assets, key=lambda x: x["weight"])[:2]
        seen_ids: set = set()
        for item in longs + shorts:
            if id(item) not in seen_ids:
                seen_ids.add(id(item))
                bars.append(item)

    bars.sort(key=lambda x: x["weight"])

    if not bars:
        return '<p style="color:#6b7280;font-style:italic">No classified positions found.</p>'

    labels = [b["label"] for b in bars]
    data   = [round(b["weight"], 2) for b in bars]
    bg_colors     = [CLASS_COLORS[b["cls"]] + "cc" for b in bars]
    border_colors = [CLASS_COLORS[b["cls"]] for b in bars]

    legend_items = []
    seen_cls: list = []
    for b in bars:
        if b["cls"] not in seen_cls:
            seen_cls.append(b["cls"])
            c = CLASS_COLORS[b["cls"]]
            legend_items.append(
                f'<span style="display:inline-flex;align-items:center;gap:4px;margin-right:12px">'
                f'<span style="width:12px;height:12px;background:{c};border-radius:2px;display:inline-block"></span>'
                f'{CLASS_LABELS[b["cls"]]}</span>'
            )
    legend_html = f'<div style="text-align:center;font-size:0.82rem;margin-bottom:0.5rem">{"".join(legend_items)}</div>'

    labels_json = json.dumps(labels)
    data_json   = json.dumps(data)
    bg_json     = json.dumps(bg_colors)
    border_json = json.dumps(border_colors)
    n_bars = len(bars)
    chart_height = max(180, n_bars * 28)

    return f"""
<div style="max-width:900px;margin:0 auto 2rem;">
  {legend_html}
  <div style="position:relative;height:{chart_height}px">
    <canvas id="posChart"></canvas>
  </div>
</div>
<script>
(function() {{
  var ctx = document.getElementById('posChart');
  new Chart(ctx, {{
    type: 'bar',
    data: {{
      labels: {labels_json},
      datasets: [{{
        label: 'Weight (%)',
        data: {data_json},
        backgroundColor: {bg_json},
        borderColor: {border_json},
        borderWidth: 1,
        borderRadius: 3,
      }}]
    }},
    options: {{
      indexAxis: 'y',
      responsive: true,
      maintainAspectRatio: false,
      plugins: {{
        legend: {{ display: false }},
        tooltip: {{
          callbacks: {{
            label: function(ctx) {{
              return ' ' + ctx.parsed.x.toFixed(2) + '%';
            }}
          }}
        }}
      }},
      scales: {{
        x: {{
          title: {{ display: true, text: 'Weight (%)' }},
          grid: {{ color: '#f3f4f6' }}
        }},
        y: {{
          ticks: {{ font: {{ family: 'monospace', size: 11 }} }}
        }}
      }}
    }}
  }});
}})();
</script>"""


def holdings_table(ticker: str, holdings: list[dict]) -> str:
    rows_html = []
    sorted_h = sorted(
        [h for h in holdings if abs(h["Weightings"]) >= 5.0],
        key=lambda h: abs(h["Weightings"]), reverse=True
    )
    for h in sorted_h:
        w = h["Weightings"]
        if is_cash(h):
            color = "#6b7280"
        elif w < 0:
            color = "#dc2626"
        else:
            color = "#16a34a"
        sign = "+" if w >= 0 else ""
        rows_html.append(
            f'<tr>'
            f'<td style="font-family:monospace">{h["StockTicker"]}</td>'
            f'<td>{h["SecurityName"]}</td>'
            f'<td style="text-align:right">${h["MarketValue"]:,.0f}</td>'
            f'<td style="text-align:right;color:{color};font-weight:600">{sign}{w:.2f}%</td>'
            f'</tr>'
        )
    return (
        f'<details open><summary style="cursor:pointer;font-size:1.1rem;font-weight:700;padding:0.5rem 0">'
        f'  {ticker} — {ETF_NAMES[ticker]}</summary>'
        f'<div style="overflow-x:auto"><table class="htable">'
        f'<thead><tr><th>Ticker</th><th>Security</th><th style="text-align:right">Market Value</th>'
        f'<th style="text-align:right">Weight</th></tr></thead>'
        f'<tbody>{"".join(rows_html)}</tbody>'
        f'</table></div></details>'
    )


def change_log_html(diffs: dict, today: str, prior_date: str | None) -> str:
    if not prior_date:
        return '<p style="color:#6b7280;font-style:italic">First snapshot — no prior data to compare.</p>'

    rows = []
    for ticker in ETF_TICKERS:
        d = diffs.get(ticker, {})
        for h in d.get("new", []):
            rows.append(f'<tr><td>{ticker}</td><td style="color:#16a34a">New</td><td>{h["StockTicker"]}</td><td>{h["SecurityName"]}</td><td style="text-align:right;color:#16a34a">+{h["Weightings"]:.2f}%</td></tr>')
        for h in d.get("removed", []):
            rows.append(f'<tr><td>{ticker}</td><td style="color:#dc2626">Removed</td><td>{h["StockTicker"]}</td><td>{h["SecurityName"]}</td><td style="text-align:right;color:#dc2626">—</td></tr>')
        for c in d.get("changed", []):
            sign = "+" if c["delta"] > 0 else ""
            color = "#16a34a" if c["delta"] > 0 else "#dc2626"
            rows.append(f'<tr><td>{ticker}</td><td style="color:{color}">Changed</td><td>{c["ticker"]}</td><td>{c["name"]}</td><td style="text-align:right;color:{color}">{sign}{c["delta"]:.2f}%</td></tr>')

    if not rows:
        return f'<p style="color:#6b7280;font-style:italic">No significant changes vs prior snapshot ({prior_date}).</p>'

    return (
        f'<p style="color:#6b7280;font-size:0.85rem">vs {prior_date}</p>'
        '<div style="overflow-x:auto"><table class="htable">'
        '<thead><tr><th>ETF</th><th>Change</th><th>Ticker</th><th>Security</th><th style="text-align:right">Δ Weight</th></tr></thead>'
        f'<tbody>{"".join(rows)}</tbody></table></div>'
    )


def extract_existing_summary() -> str:
    """Extract macro summary text from the existing report, if present."""
    out_path = REPORT_DIR / "index.html"
    if not out_path.exists():
        return ""
    html = out_path.read_text()
    import re
    m = re.search(r'<div class="summary-box">(.*?)</div>', html, re.DOTALL)
    if not m:
        return ""
    return m.group(1).replace("<br>", "\n").strip()


def render_html(today_data: dict, metrics: dict, diffs: dict, summary: str,
                snapshots: list[dict], prior_date: str | None,
                performance: dict | None = None,
                generated_at: str | None = None) -> str:
    today = today_data["date"]
    tables = "\n".join(holdings_table(t, today_data["etfs"][t]) for t in ETF_TICKERS)
    chart = aum_chart_js(snapshots)
    pos_chart = positioning_bar_chart_js(today_data)
    change_section = change_log_html(diffs, today, prior_date)
    refresh_tag = f'<p style="font-size:0.78rem;color:#9ca3af;margin-bottom:0.75rem">Last refreshed: {generated_at}</p>' if generated_at else ""
    if summary:
        summary_html = (
            f'{refresh_tag}'
            f'<div class="summary-box">{summary.replace(chr(10), "<br>")}</div>'
        )
    else:
        data_note = f" Holdings data as of {generated_at}." if generated_at else ""
        summary_html = (
            f'<p style="color:#6b7280;font-size:0.85rem;font-style:italic">{data_note}'
            f' Macro commentary is generated when running the <code>/unlimited-etfs</code> command locally.</p>'
        )

    metrics_cards = []
    for ticker in ETF_TICKERS:
        m = metrics[ticker]
        aum_m = m["net_assets"] / 1e6
        p = (performance or {}).get(ticker, {})
        ret_1m_str, ret_1m_color = fmt_ret(p.get("ret_1m"))
        ret_ytd_str, ret_ytd_color = fmt_ret(p.get("ret_ytd"))
        ret_3m_str, ret_3m_color = fmt_ret(p.get("ret_3m"))
        as_of = p.get("as_of") or ""
        as_of_label = f'<div style="font-size:0.72rem;color:#9ca3af;margin-bottom:0.25rem">as of {as_of}</div>' if as_of else ""
        perf_rows = (
            f'<div class="mc-divider"></div>'
            f'{as_of_label}'
            f'<div class="mc-row"><span>1-Month</span><span style="font-weight:700;color:{ret_1m_color}">{ret_1m_str}</span></div>'
            f'<div class="mc-row"><span>3-Month</span><span style="font-weight:700;color:{ret_3m_color}">{ret_3m_str}</span></div>'
            f'<div class="mc-row"><span>YTD</span><span style="font-weight:700;color:{ret_ytd_color}">{ret_ytd_str}</span></div>'
        ) if p else ""
        metrics_cards.append(
            f'<div class="metric-card">'
            f'<div class="mc-label">{ticker}</div>'
            f'<div class="mc-name">{ETF_NAMES[ticker]}</div>'
            f'<div class="mc-aum">${aum_m:.1f}M AUM</div>'
            f'{perf_rows}'
            f'<div class="mc-divider"></div>'
            f'<div class="mc-row"><span>Net Exposure</span><span style="font-weight:700">{m["net_exposure"]:.1f}%</span></div>'
            f'<div class="mc-row"><span>Gross Long</span><span style="color:#16a34a">{m["gross_long"]:.1f}%</span></div>'
            f'<div class="mc-row"><span>Gross Short</span><span style="color:#dc2626">{m["gross_short"]:.1f}%</span></div>'
            f'<div class="mc-row"><span>Cash</span><span style="color:#6b7280">{m["cash_pct"]:.1f}%</span></div>'
            f'</div>'
        )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Unlimited ETFs — Holdings Monitor</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #fafafa; color: #1a1a1a; line-height: 1.6; }}
    .container {{ max-width: 1100px; margin: 0 auto; padding: 2rem 1.5rem; }}
    h1 {{ font-size: 1.8rem; font-weight: 800; margin-bottom: 0.25rem; }}
    .subtitle {{ color: #6b7280; font-size: 0.9rem; margin-bottom: 2rem; }}
    h2 {{ font-size: 1.2rem; font-weight: 700; margin: 2rem 0 0.75rem; border-bottom: 2px solid #e5e7eb; padding-bottom: 0.4rem; }}
    .metrics-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 1rem; margin-bottom: 2rem; }}
    .metric-card {{ background: #fff; border: 1px solid #e5e7eb; border-radius: 8px; padding: 1rem; }}
    .mc-label {{ font-size: 1.3rem; font-weight: 800; color: #1a1a1a; }}
    .mc-name {{ font-size: 0.78rem; color: #6b7280; margin-bottom: 0.5rem; }}
    .mc-aum {{ font-size: 0.9rem; font-weight: 600; margin-bottom: 0.5rem; color: #374151; }}
    .mc-row {{ display: flex; justify-content: space-between; font-size: 0.82rem; padding: 0.1rem 0; }}
    .mc-divider {{ border-top: 1px solid #f3f4f6; margin: 0.4rem 0; }}
    .summary-box {{ background: #fff; border: 1px solid #e5e7eb; border-radius: 8px; padding: 1.5rem; font-size: 0.95rem; line-height: 1.8; }}
    .htable {{ width: 100%; border-collapse: collapse; font-size: 0.85rem; background: #fff; }}
    .htable th {{ background: #f3f4f6; font-weight: 600; padding: 0.5rem 0.75rem; text-align: left; border-bottom: 2px solid #e5e7eb; }}
    .htable td {{ padding: 0.4rem 0.75rem; border-bottom: 1px solid #f3f4f6; }}
    .htable tr:hover td {{ background: #f9fafb; }}
    details {{ margin-bottom: 1rem; background: #fff; border: 1px solid #e5e7eb; border-radius: 8px; padding: 0.75rem 1rem; }}
    details summary {{ list-style: none; }}
    details summary::-webkit-details-marker {{ display: none; }}
    footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e5e7eb; font-size: 0.78rem; color: #9ca3af; }}
  </style>
</head>
<body>
<div class="container">
  <h1>📊 Unlimited ETFs — Holdings Monitor</h1>
  <p class="subtitle">Data as of {today} · HFND · HFGM · HFMF · HFEQ</p>

  <h2>Portfolio Snapshot</h2>
  <div class="metrics-grid">
    {"".join(metrics_cards)}
  </div>

  <h2>AUM History</h2>
  {chart}

  <h2>Asset Class Positioning — Top Longs &amp; Shorts</h2>
  <p style="font-size:0.82rem;color:#6b7280;margin-bottom:0.75rem">Top 2 longs and shorts per asset class across all ETFs, sorted low to high. Color = asset class.</p>
  {pos_chart}

  <h2>Macro Summary</h2>
  {summary_html}

  <h2>Position Changes</h2>
  {change_section}

  <h2>Current Holdings</h2>
  {tables}

  <footer>
    Source: <a href="https://unlimitedetfs.com" target="_blank">unlimitedetfs.com</a> ·
    Generated by Claude Code ·
    <a href="https://github.com/DataVizHonduran/boquin.github.io" target="_blank">Source</a>
  </footer>
</div>
</body>
</html>"""

# ── Publishing ─────────────────────────────────────────────────────────────────

LANDING_CARD = """<article class="dashboard-card">
    <div class="card-header">
        <h3>📊 Unlimited ETFs — Holdings Monitor</h3>
        <p>Daily holdings tracker for HFND, HFGM, HFMF, and HFEQ with 20-day rolling archive, position change log, and AI-generated macro commentary.</p>
    </div>
    <div class="card-actions">
        <a href="reports/unlimited-etfs/index.html" class="btn btn-primary">Launch Dashboard</a>
        <a href="https://github.com/DataVizHonduran/boquin.github.io/tree/main/scripts/unlimited_etfs.py" class="btn btn-secondary">Source Code</a>
    </div>
</article>"""


def add_landing_card():
    if not LANDING_PAGE.exists():
        return
    content = LANDING_PAGE.read_text()
    if "unlimited-etfs" in content:
        return  # Already present
    # Insert before closing </div></section></main>
    marker = '            </div>\n        </section>\n    </main>'
    if marker not in content:
        print("  ⚠ Could not find landing page insertion point; skipping card addition")
        return
    card_indented = '\n'.join('                ' + line if line.strip() else line for line in LANDING_CARD.strip().split('\n'))
    updated = content.replace(marker, f'{card_indented}\n            </div>\n        </section>\n    </main>', 1)
    LANDING_PAGE.write_text(updated)
    print("  ✓ Added landing card to index.html")


def publish(today: str, added_landing_card: bool):
    repo = Path.home() / "boquin.github.io"
    files = [str(REPORT_DIR / "index.html")]
    if added_landing_card:
        files.append(str(LANDING_PAGE))

    cmds = [
        ["git", "-C", str(repo), "pull"],
        ["git", "-C", str(repo), "add"] + files,
        ["git", "-C", str(repo), "commit", "-m", f"Update Unlimited ETFs Holdings Monitor — {today}"],
        ["git", "-C", str(repo), "pull", "--rebase"],
        ["git", "-C", str(repo), "push"],
    ]
    for cmd in cmds:
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"  ⚠ git error: {result.stderr.strip()}", file=sys.stderr)
        else:
            print(f"  ✓ {' '.join(cmd[3:])}")

# ── Gemma commentary ─────────────────────────────────────────────────────────

def load_summary_meta() -> dict:
    if SUMMARY_META_FILE.exists():
        try:
            return json.loads(SUMMARY_META_FILE.read_text())
        except Exception:
            pass
    return {}


def save_summary_meta(generated_at: str, word_count: int):
    SUMMARY_META_FILE.parent.mkdir(parents=True, exist_ok=True)
    SUMMARY_META_FILE.write_text(json.dumps({
        "generated_at": generated_at,
        "word_count": word_count,
    }, indent=2))


def should_refresh_summary() -> bool:
    meta = load_summary_meta()
    if not meta.get("generated_at"):
        return True
    try:
        last = datetime.strptime(meta["generated_at"][:10], "%Y-%m-%d").date()
        return (date.today() - last).days >= SUMMARY_REFRESH_DAYS
    except Exception:
        return True


def generate_summary_gemma(context_text: str, hf_token: str, retries: int = 5) -> str:
    client = InferenceClient(model=MODEL_ID, token=hf_token, timeout=300)
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": (
            "Please analyse the following ETF positioning snapshot and write your commentary:\n\n"
            + context_text
        )},
    ]
    for attempt in range(retries):
        try:
            response = client.chat.completions.create(
                messages=messages,
                temperature=0.3,
                max_tokens=700,
                stream=False,
            )
            text = response.choices[0].message.content or ""
            if not text.strip():
                raise ValueError("Gemma returned empty response")
            return text.strip()
        except Exception as e:
            is_rate_limit = "429" in str(e) or "Too Many Requests" in str(e)
            if attempt < retries - 1:
                wait = 60 * (attempt + 1) if is_rate_limit else 10
                print(f"  Gemma attempt {attempt+1}/{retries} failed ({e}), retrying in {wait}s...",
                      file=sys.stderr)
                time.sleep(wait)
            else:
                raise


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--cache-only", action="store_true")
    parser.add_argument("--no-publish", action="store_true")
    parser.add_argument("--print-context", action="store_true", help="Print JSON context for Claude and exit")
    parser.add_argument("--summary-file", type=str, help="Path to file containing the summary text")
    args = parser.parse_args()

    today = date.today().strftime("%Y-%m-%d")
    today_path = snapshot_path(today)

    # Step 1: Load or fetch data
    if args.cache_only or today_path.exists():
        if today_path.exists():
            print(f"Loading today's snapshot from cache: {today_path.name}")
            with open(today_path) as f:
                today_data = json.load(f)
        else:
            # cache-only but no today snapshot — use latest
            files = sorted(CACHE_DIR.glob("*.json"))
            if not files:
                print("ERROR: No cached snapshots found.", file=sys.stderr)
                sys.exit(1)
            print(f"Cache-only mode: loading {files[-1].name}")
            with open(files[-1]) as f:
                today_data = json.load(f)
            today = today_data["date"]
    else:
        print("Fetching holdings CSVs...")
        etf_data = {}
        for ticker in ETF_TICKERS:
            rows = fetch_csv(ticker)
            if rows is None:
                # Fall back to latest cache for this ETF
                files = sorted(CACHE_DIR.glob("*.json"))
                for cf in reversed(files):
                    with open(cf) as fh:
                        cached = json.load(fh)
                    if ticker in cached.get("etfs", {}):
                        etf_data[ticker] = cached["etfs"][ticker]
                        print(f"  ↩ {ticker}: using cached data from {cached['date']}")
                        break
                else:
                    etf_data[ticker] = []
            else:
                etf_data[ticker] = rows

        today_data = {"date": today, "etfs": etf_data}
        save_snapshot(today_data, today)

    # Step 2: Load prior snapshot for diff
    prior_snapshot = latest_snapshot_before(today)
    prior_date = prior_snapshot["date"] if prior_snapshot else None

    # Step 3: Compute metrics and diffs
    metrics = {ticker: compute_etf_metrics(today_data["etfs"][ticker]) for ticker in ETF_TICKERS}
    diffs = {}
    if prior_snapshot:
        for ticker in ETF_TICKERS:
            diffs[ticker] = compute_diff(
                today_data["etfs"][ticker],
                prior_snapshot["etfs"].get(ticker, [])
            )

    # --print-context mode: emit JSON for Claude to summarize, then exit
    if args.print_context:
        print_context_for_claude(today_data, metrics, diffs, prior_date)
        return

    # Step 4: Load summary from file (written by Claude), auto-refresh via Gemma, or preserve
    summary = ""
    fresh_summary = False
    if args.summary_file:
        summary = Path(args.summary_file).read_text().strip()
        print(f"  ✓ Summary loaded from {args.summary_file} ({len(summary.split())} words)")
        fresh_summary = True
    else:
        hf_token = os.environ.get("HF_TOKEN")
        if hf_token and should_refresh_summary():
            meta = load_summary_meta()
            last_date = meta.get("generated_at", "never")
            print(f"  ↻ Commentary stale (last: {last_date}), refreshing via Gemma 4...")
            context_text = build_gemma_context(today_data, metrics, window_days=SUMMARY_REFRESH_DAYS)
            try:
                summary = generate_summary_gemma(context_text, hf_token)
                save_summary_meta(datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"), len(summary.split()))
                print(f"  ✓ Gemma summary generated ({len(summary.split())} words)")
                fresh_summary = True
            except Exception as e:
                print(f"  WARNING: Gemma generation failed ({e}), falling back to existing summary",
                      file=sys.stderr)
                summary = extract_existing_summary()
        else:
            summary = extract_existing_summary()
            if summary:
                print(f"  ✓ Preserved existing macro summary ({len(summary.split())} words)")
            else:
                print("  ℹ No existing summary to preserve")

    # Step 5: Fetch performance and render HTML
    print("Fetching ETF performance...")
    performance = fetch_performance()
    for ticker, p in performance.items():
        if p["ret_1m"] is not None:
            r1, _ = fmt_ret(p["ret_1m"])
            r3, _ = fmt_ret(p["ret_3m"])
            ry, _ = fmt_ret(p["ret_ytd"])
            print(f"  {ticker}: 1M {r1}  3M {r3}  YTD {ry}  (as of {p['as_of']})")

    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC") if fresh_summary else None
    all_snapshots = load_snapshots()
    html = render_html(today_data, metrics, diffs, summary, all_snapshots, prior_date, performance, generated_at)
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = REPORT_DIR / "index.html"
    out_path.write_text(html)
    print(f"  ✓ Report written: {out_path}")

    # Step 6: Publish
    if not args.no_publish:
        added_card = False
        if LANDING_PAGE.exists():
            content = LANDING_PAGE.read_text()
            if "unlimited-etfs" not in content:
                add_landing_card()
                added_card = True
        print("Publishing to boquin.github.io...")
        publish(today, added_card)
        print(f"  ✓ Published: https://boquin.xyz/reports/unlimited-etfs/")
    else:
        print("Skipping publish (--no-publish).")


if __name__ == "__main__":
    main()
